//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_$s7Economy8PowerupsC18MarketingBadgeViewCN.h"

@interface _$s7Economy8PowerupsC18MarketingBadgeViewCN (Reddit)
+ (id)powerupsMarketingViewIn:(id)arg1 post:(id)arg2 powerupsInfo:(id)arg3;
@end

