//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionReusableView.h>

__attribute__((visibility("hidden")))
@interface _TtCC7Economy8Powerups32MarketingHeaderSupplementaryView : UICollectionReusableView
{
    // Error parsing type: , name: powerupImageView
    // Error parsing type: , name: communityImageView
    // Error parsing type: , name: titleLabel
    // Error parsing type: , name: descriptionLabel
}

- (void).cxx_destruct;
- (void)prepareForReuse;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

