//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC6Reddit16ShadowBorderView.h"

@interface _TtCC6Reddit27AwardedCommentHighlightNode13HighlightView : _TtC6Reddit16ShadowBorderView
{
    // Error parsing type: , name: bubblingTimer
    // Error parsing type: , name: isBubbling
    // Error parsing type: , name: bubbleImage
    // Error parsing type: , name: bubbleCell
    // Error parsing type: , name: bubbleLayer
}

- (void).cxx_destruct;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;

@end

