//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface _TtC12RedditWalletP33_BAF490B1F30D218750AB5F300D061FE318CreatingWalletView : UIView
{
    // Error parsing type: , name: themeProvider
    // Error parsing type: , name: notchView
    // Error parsing type: , name: navigationBarView
    // Error parsing type: , name: titleLabel
    // Error parsing type: , name: contentView
    // Error parsing type: , name: disposeBag
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;

@end

