//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC6Reddit14AwardSelection : NSObject
{
}

+ (void)presentTrayInto:(id)arg1 subredditName:(id)arg2 postPK:(id)arg3 redditService:(id)arg4 theme:(id)arg5 getCoins:(CDUnknownBlockType)arg6 completion:(CDUnknownBlockType)arg7;
- (id)init;

@end

