//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class Account, AccountManager, AnalyticsManager, ExperimentManager, RUI, RedditService, VisibilityTracker, _TtC6Reddit20AnonymousModeManager;
@protocol ViewContext;

@interface _TtC6Reddit20RedditAccountContext : NSObject
{
    // Error parsing type: , name: accountManager
    // Error parsing type: , name: redditService
    // Error parsing type: , name: rui
    // Error parsing type: , name: analyticsManager
    // Error parsing type: , name: visibilityTracker
    // Error parsing type: , name: anonymousModeManager
}

- (void).cxx_destruct;
- (id)init;
@property(nonatomic, readonly) ExperimentManager *experimentManager;
@property(nonatomic, readonly) Account *account;
@property(nonatomic, readonly) id <ViewContext> viewContext;
- (id)initWithAccountManager:(id)arg1 anonymousModeManager:(id)arg2 redditService:(id)arg3 rui:(id)arg4 analyticsManager:(id)arg5 visibilityTracker:(id)arg6;
@property(nonatomic, readonly) _TtC6Reddit20AnonymousModeManager *anonymousModeManager; // @synthesize anonymousModeManager;
@property(nonatomic, readonly) VisibilityTracker *visibilityTracker; // @synthesize visibilityTracker;
@property(nonatomic, readonly) AnalyticsManager *analyticsManager; // @synthesize analyticsManager;
@property(nonatomic, readonly) RUI *rui; // @synthesize rui;
@property(nonatomic, readonly) RedditService *redditService; // @synthesize redditService;
@property(nonatomic, readonly) AccountManager *accountManager; // @synthesize accountManager;

@end

