//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class RedditService;

@interface _TtC6Reddit25StreamingHeartbeatService : NSObject
{
    // Error parsing type: , name: redditService
}

- (void).cxx_destruct;
- (id)init;
- (void)sendHeartbeatForLiveStreamPost:(id)arg1;
- (void)sendHeartbeat:(id)arg1;
- (id)initWithRedditService:(id)arg1;
@property(nonatomic, readonly) RedditService *redditService; // @synthesize redditService;

@end

