//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <RedditUI/BaseView.h>

@class BaseButton, _TtC6Reddit13PostTagToggle;

@interface _TtC6Reddit25PostKeyboardAccessoryView : BaseView
{
    // Error parsing type: , name: linkButton
    // Error parsing type: , name: $__lazy_storage_$_nsfwTag
    // Error parsing type: , name: $__lazy_storage_$_spoilerTag
    // Error parsing type: , name: viewContext
    // Error parsing type: , name: overflowButton
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)overflowButonPress;
- (void)configureWithPostToEdit:(id)arg1;
- (void)configureWithSubreddit:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithViewContext:(id)arg1 frame:(struct CGRect)arg2;
@property(nonatomic, retain) _TtC6Reddit13PostTagToggle *spoilerTag;
@property(nonatomic, retain) _TtC6Reddit13PostTagToggle *nsfwTag;
@property(nonatomic, readonly) BaseButton *linkButton; // @synthesize linkButton;

@end

