//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "PostViewController.h"

@class NSString;

@interface _TtC6Reddit30MediaGalleryPostViewController : PostViewController
{
    // Error parsing type: , name: annotatedImages
    // Error parsing type: , name: captionsButton
    // Error parsing type: , name: orderingViewController
    // Error parsing type: , name: stackView
}

- (void).cxx_destruct;
- (id)initWithAccountContext:(id)arg1;
- (void)didTapCaptionsButton;
- (id)analyticsPostComposerType;
@property(nonatomic, readonly) NSString *analyticsScreenViewName;
- (void)dealloc;
- (void)viewDidLoad;

@end

