//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface _TtCC6Reddit14AwardSelection13MessageEditor : UIView
{
    // Error parsing type: , name: theme
    // Error parsing type: , name: isActive
    // Error parsing type: , name: _isAnonymous
    // Error parsing type: , name: didChangeIsAnonymous
    // Error parsing type: , name: allowsAnonymous
    // Error parsing type: , name: _message
    // Error parsing type: , name: award
    // Error parsing type: , name: didChangeMessage
    // Error parsing type: , name: ctaButtonLayoutGuide
    // Error parsing type: , name: anonymousToggleImageView
    // Error parsing type: , name: anonymousToggleLabel
    // Error parsing type: , name: textView
    // Error parsing type: , name: textViewHeightConstraint
    // Error parsing type: , name: placeholderLabel
    // Error parsing type: , name: messageLimitLabel
    // Error parsing type: , name: activeStateConstrains
    // Error parsing type: , name: inactiveStateConstrains
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)textViewDidChange:(id)arg1;
- (void)textViewDidEndEditing:(id)arg1;
- (void)textViewDidBeginEditing:(id)arg1;
- (void)deactivate;
- (void)toggleIsAnonymous;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end

