//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface _TtC6RedditP33_8B80A23E8BECBF8AE5AE08C646EA78AB20BottomSheetLoginView : UIView
{
    // Error parsing type: , name: titleView
    // Error parsing type: , name: loginButton
    // Error parsing type: , name: stackView
    // Error parsing type: , name: delegate
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)didTapLoginButtonWithSender:(id)arg1;
- (void)didTapEmailButtonWithSender:(id)arg1;
- (void)didTapAppleButtonWithSender:(id)arg1;
- (void)didTapGoogleButtonWithSender:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

