//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "AccountContext-Protocol.h"
#import "ViewContext-Protocol.h"

@class Account, AnalyticsManager, ExperimentManager, RUI, RedditService, VisibilityTracker;
@protocol ViewContext;

@interface _TtC6Reddit20RedditAccountContext : NSObject <AccountContext, ViewContext>
{
    // Error parsing type: , name: redditService
    // Error parsing type: , name: rui
    // Error parsing type: , name: analyticsManager
    // Error parsing type: , name: visibilityTracker
}

- (void).cxx_destruct;
- (id)init;
@property(nonatomic, readonly) ExperimentManager *experimentManager;
@property(nonatomic, readonly) Account *account;
@property(nonatomic, readonly) id <ViewContext> viewContext;
- (id)initWithRedditService:(id)arg1 rui:(id)arg2 analyticsManager:(id)arg3 visibilityTracker:(id)arg4;
@property(nonatomic, readonly) VisibilityTracker *visibilityTracker; // @synthesize visibilityTracker;
@property(nonatomic, readonly) AnalyticsManager *analyticsManager; // @synthesize analyticsManager;
@property(nonatomic, readonly) RUI *rui; // @synthesize rui;
@property(nonatomic, readonly) RedditService *redditService; // @synthesize redditService;

@end

