//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

__attribute__((visibility("hidden")))
@interface _TtC12RedditWallet21WalletFeedContentView : UIView
{
    // Error parsing type: , name: notchView
    // Error parsing type: , name: navigationView
    // Error parsing type: , name: navigationHeaderView
    // Error parsing type: , name: contentScrollView
    // Error parsing type: , name: balanceView
    // Error parsing type: , name: staticCardView
    // Error parsing type: , name: newPointsView
    // Error parsing type: , name: usePointsView
    // Error parsing type: , name: transactionListView
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;

@end

