//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC12RedditWalletP33_925BE7F441428AC4AF621C5F7ABABE1118BundleLocatorDummy : NSObject
{
}

- (id)init;

@end

