//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class PremiumCancelOffer, PremiumSubscriptionInfo;

@interface _TtC6Reddit32RedditPremiumSettingsCoordinator : NSObject
{
    // Error parsing type: , name: accountContext
    // Error parsing type: , name: dataSource
    // Error parsing type: , name: testing
    // Error parsing type: , name: subscriber
    // Error parsing type: , name: offerScreen
    // Error parsing type: , name: subscriptionUpdated
    // Error parsing type: , name: goldEventLogger
    // Error parsing type: , name: cancelOffer
    // Error parsing type: , name: subscriptionInfo
}

- (void).cxx_destruct;
- (id)init;
- (id)getOfferScreen;
- (_Bool)showOfferAccepted;
- (_Bool)showManageScreen;
- (id)initWithAccountContext:(id)arg1 dataSource:(id)arg2 subscriber:(_Bool)arg3 goldEventLogger:(id)arg4 testing:(_Bool)arg5 subscriptionUpdated:(CDUnknownBlockType)arg6;
@property(nonatomic, retain) PremiumSubscriptionInfo *subscriptionInfo; // @synthesize subscriptionInfo;
@property(nonatomic, retain) PremiumCancelOffer *cancelOffer; // @synthesize cancelOffer;

@end

