//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "_TtP7Economy25EconomyDependencyProvider_-Protocol.h"

@class AccountManager, AppSettings;

@interface _TtC6Reddit31RedditEconomyDependencyProvider : NSObject <_TtP7Economy25EconomyDependencyProvider_>
{
    // Error parsing type: , name: accountManager
    // Error parsing type: , name: appSettings
}

- (void).cxx_destruct;
- (id)init;
@property(nonatomic, readonly) _Bool inAppPurchaseSkipReceiptValidation;
@property(nonatomic, readonly) _Bool inAppPurchaseForceDeferredTransaction;
- (_Bool)isInAnonymousBrowsingWithRedditService:(id)arg1;
- (id)economyAnalyticsLoggerWithRedditService:(id)arg1;
- (id)initWithAccountManager:(id)arg1 appSettings:(id)arg2;
@property(nonatomic, readonly) AppSettings *appSettings; // @synthesize appSettings;
@property(nonatomic, readonly) AccountManager *accountManager; // @synthesize accountManager;

@end

