//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface _TtC7Economy20AwardSelectionConfig : NSObject
{
    // Error parsing type: , name: preselectedAwardId
    // Error parsing type: , name: shouldAllowEditOptions
    // Error parsing type: , name: shouldAllowAnonymousGilding
    // Error parsing type: , name: shouldShowChatBox
    // Error parsing type: , name: shouldCloseAwardSelectionBeforeCompletion
}

+ (id)defaultPreselectedAwardID;
- (void).cxx_destruct;
- (id)init;
- (id)copyWithZone:(void *)arg1;
@property(nonatomic) _Bool shouldCloseAwardSelectionBeforeCompletion; // @synthesize shouldCloseAwardSelectionBeforeCompletion;
@property(nonatomic) _Bool shouldShowChatBox; // @synthesize shouldShowChatBox;
@property(nonatomic) _Bool shouldAllowAnonymousGilding; // @synthesize shouldAllowAnonymousGilding;
@property(nonatomic) _Bool shouldAllowEditOptions; // @synthesize shouldAllowEditOptions;
@property(nonatomic, copy) NSString *preselectedAwardId;

@end

