//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AsyncDisplayKit/ASDisplayNode.h>

@interface _TtCC6Reddit39MetaPaywallPaymentMethodsViewControllerP33_7122717A78D432793DDF44DF0759738911BalanceNode : ASDisplayNode
{
    // Error parsing type: , name: warningIconNode
    // Error parsing type: , name: warningLabel
    // Error parsing type: , name: explanationLabel
    // Error parsing type: , name: balanceLabel
    // Error parsing type: , name: balanceIconNode
    // Error parsing type: , name: balanceAmountLabel
    // Error parsing type: , name: balanceContainer
}

- (void).cxx_destruct;
- (id)init;
- (id)layoutSpecThatFits:(CDStruct_90e057aa)arg1;

@end

