//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface _TtCOE6RedditO8RedditUI13RUIComponents4AuthP33_213AD7D6391E119724DBF1B93354BF4B12ProviderView : UIView
{
    // Error parsing type: , name: provider
}

- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;

@end

