//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <Economy/_TtP8RedditUI33BottomSheetViewControllerDelegate_-Protocol.h>

@interface _TtCC7Economy8Awarding6FlowV2 : NSObject <_TtP8RedditUI33BottomSheetViewControllerDelegate_>
{
    // Error parsing type: , name: awardable
    // Error parsing type: , name: awardingService
    // Error parsing type: , name: eventLogger
    // Error parsing type: , name: delegate
    // Error parsing type: , name: props
    // Error parsing type: , name: state
    // Error parsing type: , name: bottomSheetViewController
    // Error parsing type: , name: navigationController
    // Error parsing type: , name: selectionViewController
}

- (void).cxx_destruct;
- (id)init;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (void)didExpandToFullSheet;
- (void)onExpandToFullSheet;
- (void)willExpandToFullSheet;

@end

