//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface _TtCC6Reddit21MetaPaywallFooterViewP33_50286BB6ADAB27AB8EFEF43B13FFF0819PriceView : UIView
{
    // Error parsing type: , name: imageNode
    // Error parsing type: , name: labelNode
    // Error parsing type: , name: containerNode
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;
@property(nonatomic, readonly) struct CGSize intrinsicContentSize;

@end

