//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIButton.h>

@interface _TtCZFOE6RedditO8RedditUI13RUIComponents4Auth16defaultSSOButtonFT3ruiCSo3RUI6heightV12CoreGraphics7CGFloat_CSo8UIButtonL_21LeftAlignedIconButton : UIButton
{
}

- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (struct CGRect)imageRectForContentRect:(struct CGRect)arg1;

@end

