//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface _TtCC12RedditWalletP33_D05266233EE2CAE0173672F49B92563C35RecoveryPhraseCopyMnemonicStackView8WordView : UIView
{
    // Error parsing type: , name: indexLabel
    // Error parsing type: , name: stringLabel
    // Error parsing type: , name: cancellables
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;

@end

