//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtC12RedditWallet31TokenClaimProcessFlowController : _TtCs12_SwiftObject
{
    // Error parsing type: , name: claim
    // Error parsing type: , name: ethereumProvider
    // Error parsing type: , name: gsnClient
    // Error parsing type: , name: service
    // Error parsing type: , name: wallet
    // Error parsing type: , name: repository
    // Error parsing type: , name: themeProvider
    // Error parsing type: , name: imageProvider
}

@end

