//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtCC12RedditWallet28WalletTransferFlowControllerP33_44E250608DD45B73931B5A752A3D8EDD12Subscription : _TtCs12_SwiftObject
{
    // Error parsing type: , name: disposeBag
}

@end

