//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SimpleAttributedLabelViewController.h"

@interface _TtC6Reddit28SubredditRulesViewController : SimpleAttributedLabelViewController
{
    // Error parsing type: , name: subreddit
    // Error parsing type: , name: spinner
}

- (void).cxx_destruct;
- (id)initWithAccountContext:(id)arg1;
- (void)spinnerPressedWithSender:(id)arg1;
- (void)viewDidLoad;
- (id)initWithAccountContext:(id)arg1 subreddit:(id)arg2;

@end

