//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC6Reddit24RedditCinemaFeedPostNode.h"

@interface _TtC6Reddit24RedditCinemaFeedPostNode (Reddit)
- (struct CGSize)mediaSizeWithTargetWidth:(double)arg1;
- (void)resignFocusedMedia;
- (void)becomeFocusedMediaWithIsMuted:(_Bool)arg1;
- (id)layoutSpecThatFits:(CDStruct_90e057aa)arg1;
- (void)didLoad;
@end

