//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Economy/_TtCCC7Economy8Awarding6FlowV28BaseView.h>

#import <Economy/UIGestureRecognizerDelegate-Protocol.h>

@interface _TtCCC7Economy8Awarding6FlowV2P33_A2325753FB487A69662B99E3E592916113SelectionView : _TtCCC7Economy8Awarding6FlowV28BaseView <UIGestureRecognizerDelegate>
{
    // Error parsing type: , name: handleView
    // Error parsing type: , name: headerView
    // Error parsing type: , name: miniPillBar
    // Error parsing type: , name: awardList
    // Error parsing type: , name: awardInfoView
    // Error parsing type: , name: awardListTopSeparatorView
    // Error parsing type: , name: awardListBottomSeparatorView
    // Error parsing type: , name: swipeInfo
}

- (void).cxx_destruct;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (void)panWithGesture:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

