//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC6Reddit26RedditCinemaViewController.h"

@interface _TtC6Reddit26RedditCinemaViewController (Reddit1)
- (void)feedPostAwardsNode:(id)arg1 didTapAwardsForPost:(id)arg2 award:(id)arg3;
- (void)feedPostCommentBarNodeDidTapActionButton:(id)arg1;
- (void)feedPostCommentBarNodeDidTapAwardButton:(id)arg1;
- (void)feedPostCommentBarNodeDidTapComment:(id)arg1;
- (void)feedPostCommentBarNodeDidTapDownvote:(id)arg1;
- (void)feedPostCommentBarNodeDidTapUpvote:(id)arg1;
- (void)didTapCallToActionFromRedditVideoPlayerView:(id)arg1 post:(id)arg2 callToAction:(id)arg3;
- (void)didTapFullscreenViewFromRedditVideoPlayerView:(id)arg1 post:(id)arg2;
- (void)didTapTimeIndicatorFromRedditVideoPlayerView:(id)arg1 post:(id)arg2;
- (void)didTapViewFromRedditVideoPlayerView:(id)arg1 post:(id)arg2 videoIsLive:(_Bool)arg3;
- (void)feedPostEventBarNodeDidTapFollowEvent:(id)arg1;
- (void)feedPostTitleNodeDidTapReport:(id)arg1;
- (void)feedPostTitleNode:(id)arg1 didTapOverflowButton:(id)arg2;
- (void)feedPostTitleNodeDidTapSubscribeButton:(id)arg1;
- (void)feedPostTitleNode:(id)arg1 didTapLinkURL:(id)arg2 context:(unsigned long long)arg3;
- (void)cellNodeDidTap:(id)arg1;
@end

