//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC6Reddit25BaseLiveStreamDetailsView.h"

@interface _TtC6Reddit23LiveStreamDetailsViewV2 : _TtC6Reddit25BaseLiveStreamDetailsView
{
    // Error parsing type: , name: kChatEntryViewHeight
    // Error parsing type: , name: animationDuration
    // Error parsing type: , name: kJoinButtonHeight
    // Error parsing type: , name: errorLabel
    // Error parsing type: , name: bottomContainer
    // Error parsing type: , name: $__lazy_storage_$_liveOrVODIndicator
    // Error parsing type: , name: $__lazy_storage_$_subredditPickerButton
    // Error parsing type: , name: $__lazy_storage_$_joinButton
    // Error parsing type: , name: titleLabel
    // Error parsing type: , name: viewerCountLabel
    // Error parsing type: , name: bottomGradientView
    // Error parsing type: , name: bottomGradientHeightConstraint
    // Error parsing type: , name: progressView
    // Error parsing type: , name: chatEntryView
    // Error parsing type: , name: sideBar
    // Error parsing type: , name: liveStream
    // Error parsing type: , name: lastLiveState
    // Error parsing type: , name: shouldHideJoinButton
    // Error parsing type: , name: isAllUIHidden
    // Error parsing type: , name: elapsed
    // Error parsing type: , name: duration
    // Error parsing type: , name: isUserScrubbing
    // Error parsing type: , name: playAfterScrub
    // Error parsing type: , name: service
    // Error parsing type: , name: visibilityDelegate
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)didTapLiveIndicator;
- (void)didTapSubredditPickerButton;
- (void)didTapJoin;
- (id)initWithCoder:(id)arg1;

@end

