//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC6Reddit24CoinMarketingEventLogger : NSObject
{
    // Error parsing type: , name: correlationId
    // Error parsing type: , name: analyticsManager
    // Error parsing type: , name: user
    // Error parsing type: , name: isPremiumSubscriber
    // Error parsing type: , name: didLogScreenViewEvent
}

- (void).cxx_destruct;
- (id)init;
- (void)logOfferPopupCloseEvent:(id)arg1;
- (void)logOfferPopupConfirmEvent:(id)arg1;
- (void)logOfferPopupTriggerEvent:(id)arg1;
- (void)logViewPurchaseSuccessEvent:(id)arg1 transactionId:(id)arg2;
- (void)logViewPurchaseProcessingEvent:(id)arg1;
- (void)logClickLearnMore;
- (void)logClickProductEvent:(id)arg1;
- (void)logScreenViewEvent;
- (void)logCoinSaleEntryFrom:(id)arg1;
- (id)initWithAccount:(id)arg1 analyticsManager:(id)arg2 correlationId:(id)arg3;

@end

