//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AsyncDisplayKit/ASControlNode.h>

@class AwardingTotal;

@interface _TtC6Reddit17AwardingTotalNode : ASControlNode
{
    // Error parsing type: , name: awardingTotal
    // Error parsing type: , name: options
    // Error parsing type: , name: imageNode
    // Error parsing type: , name: textNode
}

- (void).cxx_destruct;
- (id)init;
- (id)layoutSpecThatFits:(CDStruct_90e057aa)arg1;
- (void)didLoad;
- (id)initWithAwardingTotal:(id)arg1 options:(id)arg2;
@property(nonatomic, readonly) _Bool showsHighlight;
@property(nonatomic, readonly) AwardingTotal *awardingTotal; // @synthesize awardingTotal;

@end

