//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC6Reddit27SearchAnalyticsEventFactory.h"

@interface _TtC6Reddit27SearchAnalyticsEventFactory (Reddit2)
+ (id)analyticsSubredditWith:(id)arg1;
+ (id)analyticsPostWith:(id)arg1;
+ (id)searchWith:(id)arg1 flair:(id)arg2 subreddit:(id)arg3;
@end

