//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface _TtCC6Reddit14AwardSelection18AwardSelectionView : UIView
{
    // Error parsing type: , name: theme
    // Error parsing type: , name: model
    // Error parsing type: , name: isAnonymous
    // Error parsing type: , name: allowsAnonymous
    // Error parsing type: , name: sendAward
    // Error parsing type: , name: getCoins
    // Error parsing type: , name: selectedAward
    // Error parsing type: , name: message
    // Error parsing type: , name: keyboardFrame
    // Error parsing type: , name: selectedAwardView
    // Error parsing type: , name: unselectButtonContainer
    // Error parsing type: , name: unselectButton
    // Error parsing type: , name: containerView
    // Error parsing type: , name: stackView
    // Error parsing type: , name: messageEditor
    // Error parsing type: , name: awardList
    // Error parsing type: , name: coinsBar
    // Error parsing type: , name: loadingIndicatorContainer
    // Error parsing type: , name: loadingIndicator
    // Error parsing type: , name: keyboardPlaceholderView
    // Error parsing type: , name: keyboardPlaceholderViewHeightConstraint
    // Error parsing type: , name: sendAwardButton
    // Error parsing type: , name: sendAwardConstrainsForActiveKeyboard
    // Error parsing type: , name: sendAwardConstrainsForInactiveKeyboard
    // Error parsing type: , name: notificationTokens
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
- (void)sendAwardButtonTap;
- (void)discardOverlay;
- (void)unselect;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end

