//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC6Reddit26RedditCinemaViewController.h"

@interface _TtC6Reddit26RedditCinemaViewController (Reddit5)
- (void)postFeedCell:(id)arg1 didViewPost:(id)arg2 withVisibilityContext:(id)arg3;
- (void)postFeedCell:(id)arg1 didConsumePost:(id)arg2 withVisibilityContext:(id)arg3;
@end

