//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface _TtC12RedditWalletP33_42D56E778E3502669A46983D546CA97E25NewPointsSectionInnerView : UIView
{
    // Error parsing type: , name: stackView
    // Error parsing type: , name: repository
    // Error parsing type: , name: performClaimSink
    // Error parsing type: , name: performOngoingClaimSink
    // Error parsing type: , name: shouldReloadSubject
    // Error parsing type: , name: timer
    // Error parsing type: , name: disposeBag
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;

@end

