//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@protocol AccountContext;

@interface _TtC6Reddit20AnonymousModeManager : NSObject
{
    // Error parsing type: , name: kDefaultTimeoutIntervalSec
    // Error parsing type: , name: accountContext
    // Error parsing type: , name: timeoutIntervalSec
    // Error parsing type: , name: $__lazy_storage_$_anonymousModeInfo
    // Error parsing type: , name: accountManager
    // Error parsing type: , name: themeToggleClosure
    // Error parsing type: , name: welcomePopupShowingClosure
    // Error parsing type: , name: backgroundedAt
}

- (void).cxx_destruct;
- (id)init;
- (void)leaveAnonymousBrowsingModeWithCompletion:(CDUnknownBlockType)arg1;
- (void)enterAnonymousBrowsingMode;
- (id)initWithAccountManager:(id)arg1;
@property(nonatomic) double timeoutIntervalSec; // @synthesize timeoutIntervalSec;
@property(nonatomic) _Bool isInAnonymousBrowsingMode;
@property(nonatomic) __weak id <AccountContext> accountContext; // @synthesize accountContext;

@end

