//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Economy/_TtCCC7Economy8Awarding6FlowV28BaseView.h>

__attribute__((visibility("hidden")))
@interface _TtCCC7Economy8Awarding6FlowV213AwardInfoView : _TtCCC7Economy8Awarding6FlowV28BaseView
{
    // Error parsing type: , name: imageView
    // Error parsing type: , name: nameLabel
    // Error parsing type: , name: coinPriceLabel
    // Error parsing type: , name: descriptionLabel
    // Error parsing type: , name: optionsBriefView
    // Error parsing type: , name: sendButton
    // Error parsing type: , name: activityIndicator
}

- (void).cxx_destruct;
- (void)editOptions;
- (void)sendAward;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;

@end

