//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@interface _TtC6Reddit30BottomSheetLoginViewController : UIViewController
{
    // Error parsing type: , name: accountContext
    // Error parsing type: , name: accountManager
    // Error parsing type: , name: scrollView
    // Error parsing type: , name: bottomSheetLoginView
}

- (void).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithCoder:(id)arg1;
- (id)initWithAccountContext:(id)arg1;

@end

