//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

__attribute__((visibility("hidden")))
@interface _TtC12RedditWallet24WalletFeedViewController : UIViewController
{
    // Error parsing type: , name: address
    // Error parsing type: , name: wallet
    // Error parsing type: , name: actions
    // Error parsing type: , name: launchOptions
    // Error parsing type: , name: walletFlow
    // Error parsing type: , name: repository
    // Error parsing type: , name: dataSource
    // Error parsing type: , name: redditService
    // Error parsing type: , name: ethereumProvider
    // Error parsing type: , name: themeProvider
    // Error parsing type: , name: imageProvider
    // Error parsing type: , name: shouldReloadSubject
    // Error parsing type: , name: timer
    // Error parsing type: , name: $__lazy_storage_$_contentView
    // Error parsing type: , name: $__lazy_storage_$_delayedClaimHandler
    // Error parsing type: , name: disposeBag
}

- (void).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)loadView;
- (id)initWithCoder:(id)arg1;

@end

