//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface _TtCC12RedditWallet31TransactionStatusViewControllerP33_5AF591A5106BC6A6BD314BC71454350E4View : UIView
{
    // Error parsing type: , name: content
    // Error parsing type: , name: contentContainer
    // Error parsing type: , name: doneButton
    // Error parsing type: , name: disposeBag
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;

@end

