//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtC12RedditWallet16WalletDataSource : _TtCs12_SwiftObject
{
    // Error parsing type: , name: ongoingTransactionStorage
    // Error parsing type: , name: subredditCache
    // Error parsing type: , name: subscribedSubredditCache
    // Error parsing type: , name: userResponseCache
    // Error parsing type: , name: communitiesCache
    // Error parsing type: , name: transactionsCache
    // Error parsing type: , name: metaSubredditCache
    // Error parsing type: , name: metaMembershipProductCache
}

@end

