//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface _TtC6Reddit24AnnouncementCarouselView : UIView
{
    // Error parsing type: , name: kDismissCellWidth
    // Error parsing type: , name: announcements
    // Error parsing type: , name: $__lazy_storage_$_carouselPagingLayout
    // Error parsing type: , name: $__lazy_storage_$_carouselCollectionView
    // Error parsing type: , name: $__lazy_storage_$_titleLabel
    // Error parsing type: , name: $__lazy_storage_$_pageControl
}

- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

