//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class UIScrollView, UIView;

@interface _TtC8RedditUI29HeaderContainerViewController : UIViewController
{
    // Error parsing type: , name: child
    // Error parsing type: , name: headerView
    // Error parsing type: , name: observedScrollView
    // Error parsing type: , name: headerContainer
    // Error parsing type: , name: scrollViewObservation
}

- (void).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)showHeaderWithAnimated:(_Bool)arg1;
- (void)viewSafeAreaInsetsDidChange;
- (void)viewDidLoad;
- (id)initWithCoder:(id)arg1;
- (id)initWithChild:(id)arg1 headerView:(id)arg2;
@property(nonatomic) __weak UIScrollView *observedScrollView; // @synthesize observedScrollView;
@property(nonatomic, readonly) UIView *headerView; // @synthesize headerView;
@property(nonatomic, readonly) UIViewController *child; // @synthesize child;

@end

