//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BaseViewController.h"

@interface _TtC6Reddit29AnonymousBrowsingWelcomePopup : BaseViewController
{
    // Error parsing type: , name: corneredView
    // Error parsing type: , name: scrollViewContainerView
    // Error parsing type: , name: scrollView
    // Error parsing type: , name: stackView
    // Error parsing type: , name: imageViewContainerView
    // Error parsing type: , name: imageView
    // Error parsing type: , name: titleLabelContainerView
    // Error parsing type: , name: titleLabel
    // Error parsing type: , name: mainDescriptionContainerView
    // Error parsing type: , name: mainDescriptionLabel
    // Error parsing type: , name: learnMoreButtonContainerView
    // Error parsing type: , name: learnMoreButton
    // Error parsing type: , name: firstBulletContainerView
    // Error parsing type: , name: firstBulletView
    // Error parsing type: , name: firstBulletDescription
    // Error parsing type: , name: secondBulletContainerView
    // Error parsing type: , name: secondBulletView
    // Error parsing type: , name: secondBulletDescription
    // Error parsing type: , name: acceptButton
    // Error parsing type: , name: completionBlock
}

- (void).cxx_destruct;
- (void)viewDidLoad;
- (id)initWithCompletionBlock:(CDUnknownBlockType)arg1;
- (id)init;

@end

