//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <RedditVideo/_TtC11RedditVideo16PlayerController.h>

@interface _TtC11RedditVideo16PlayerController (RedditVideo1)
- (void)elapsedTimeDidUpdateWithPlayer:(id)arg1 time:(CDStruct_198678f7)arg2;
@end

