//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class BaseTextView, NSLayoutYAxisAnchor;
@protocol _TtP6Reddit27CommentComposerViewDelegate_;

@interface _TtC6Reddit29CommentComposerViewController : UIViewController
{
    // Error parsing type: , name: headerView
    // Error parsing type: , name: topPaddingConstraint
    // Error parsing type: , name: maxTextHeightConstraint
    // Error parsing type: , name: minTextHeightConstraint
    // Error parsing type: , name: expandedTopConstraint
    // Error parsing type: , name: bottomConstraint
    // Error parsing type: , name: maxNumberOfLines
    // Error parsing type: , name: minNumberOfLines
    // Error parsing type: , name: headerHeight
    // Error parsing type: , name: toolbarHeight
    // Error parsing type: , name: edgePadding
    // Error parsing type: , name: $__lazy_storage_$_textContainerInset
    // Error parsing type: , name: service
    // Error parsing type: , name: presenter
    // Error parsing type: , name: post
    // Error parsing type: , name: commentTreeNode
    // Error parsing type: , name: isOnEditMode
    // Error parsing type: , name: bottomViewYAnchor
    // Error parsing type: , name: delegate
    // Error parsing type: , name: isExpanded
    // Error parsing type: , name: cardView
    // Error parsing type: , name: contentStackView
    // Error parsing type: , name: $__lazy_storage_$_commentTextView
    // Error parsing type: , name: $__lazy_storage_$_toolbar
}

- (void).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)configureWithCommentTreeNode:(id)arg1 isOnEditMode:(_Bool)arg2;
- (void)configureWithPost:(id)arg1;
- (void)didMoveToParentViewController:(id)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
@property(nonatomic, readonly) double composerHeight;
- (id)initWithCoder:(id)arg1;
- (id)initWithService:(id)arg1 presenter:(id)arg2;
@property(nonatomic, retain) BaseTextView *commentTextView;
@property(nonatomic) __weak id <_TtP6Reddit27CommentComposerViewDelegate_> delegate; // @synthesize delegate;
@property(nonatomic, retain) NSLayoutYAxisAnchor *bottomViewYAnchor; // @synthesize bottomViewYAnchor;

@end

