//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC6Reddit14AwardSelection : NSObject
{
}

+ (CDUnknownBlockType)viewControllerMakerWithComment:(id)arg1 post:(id)arg2 redditService:(id)arg3 eventLogger:(id)arg4 theme:(id)arg5 delegate:(id)arg6;
+ (CDUnknownBlockType)viewControllerMakerWithStream:(id)arg1 post:(id)arg2 redditService:(id)arg3 eventLogger:(id)arg4 theme:(id)arg5 delegate:(id)arg6;
+ (CDUnknownBlockType)viewControllerMakerWithPost:(id)arg1 redditService:(id)arg2 eventLogger:(id)arg3 theme:(id)arg4 delegate:(id)arg5;
- (id)init;

@end

