//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "_TtP7Economy25EconomyDependencyProvider_-Protocol.h"

@class AccountManager;
@protocol _TtP7Economy12EconSettings_;

@interface _TtC6Reddit31RedditEconomyDependencyProvider : NSObject <_TtP7Economy25EconomyDependencyProvider_>
{
    // Error parsing type: , name: accountManager
    // Error parsing type: , name: econSettings
}

- (void).cxx_destruct;
- (id)init;
- (_Bool)isInAnonymousBrowsingWithRedditService:(id)arg1;
- (id)economyAnalyticsLoggerWithRedditService:(id)arg1;
- (id)initWithAccountManager:(id)arg1 appSettings:(id)arg2;
@property(nonatomic, readonly) id <_TtP7Economy12EconSettings_> econSettings; // @synthesize econSettings;
@property(nonatomic, readonly) AccountManager *accountManager; // @synthesize accountManager;

@end

