//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_$s7Economy15BaseOverlayViewCN.h"

@interface _TtCC6Reddit26AwardBubblingHighlightNode13HighlightView : _$s7Economy15BaseOverlayViewCN
{
    // Error parsing type: , name: isBubbling
    // Error parsing type: , name: bubbleImage
    // Error parsing type: , name: bubbleCell
    // Error parsing type: , name: bubbleLayer
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end

