//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "AwardCoordinatorDelegate-Protocol.h"

@class AwardCoordinatorV2, _TtC7Economy20AwardSelectionConfig;
@protocol _TtP6Reddit19GildingFlowDelegate_;

@interface _TtC6Reddit21GildingFlowController : NSObject <AwardCoordinatorDelegate>
{
    // Error parsing type: , name: awardable
    // Error parsing type: , name: awardCoordinator
    // Error parsing type: , name: delegate
    // Error parsing type: , name: keepAliveInstance
}

- (void).cxx_destruct;
- (id)init;
- (void)awardCoordinatorDidFail:(id)arg1;
- (void)awardCoordinatorDidFinish:(id)arg1;
- (void)awardCoordinatorDidStart:(id)arg1;
- (void)startFromViewController:(id)arg1 config:(id)arg2;
@property(nonatomic, readonly) _TtC7Economy20AwardSelectionConfig *defaultConfig;
- (id)initWithComment:(id)arg1 parentPost:(id)arg2 accountContext:(id)arg3 correlationId:(id)arg4;
- (id)initWithLiveStreamPost:(id)arg1 liveStream:(id)arg2 accountContext:(id)arg3 correlationId:(id)arg4 delegate:(id)arg5;
- (id)initWithPost:(id)arg1 accountContext:(id)arg2 correlationId:(id)arg3;
@property(nonatomic) __weak id <_TtP6Reddit19GildingFlowDelegate_> delegate; // @synthesize delegate;
@property(nonatomic, readonly) AwardCoordinatorV2 *awardCoordinator; // @synthesize awardCoordinator;

@end

