//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <RedditUI/BaseView.h>

@interface _TtC6Reddit25UserKarmaAndGoldKarmaView : BaseView
{
    // Error parsing type: , name: $__lazy_storage_$_karmaGridStackView
    // Error parsing type: , name: $__lazy_storage_$_postKarmaLabel
    // Error parsing type: , name: $__lazy_storage_$_commentKarmaLabel
    // Error parsing type: , name: $__lazy_storage_$_awarderKarmaLabel
    // Error parsing type: , name: $__lazy_storage_$_awardeeKarmaLabel
    // Error parsing type: , name: bottomLine
}

+ (double)defaultHeight;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)configureWith:(id)arg1;

@end

