//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC6Reddit30FlairManagementViewController1.h"

#import "EditFlairViewControllerDelegate-Protocol.h"

@interface _TtC6Reddit30FlairManagementViewController1 (Reddit3) <EditFlairViewControllerDelegate>
- (void)editFlairViewController:(id)arg1 didDeleteFlair:(id)arg2;
- (void)editFlairViewController:(id)arg1 didEditFlair:(id)arg2;
@end

