//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BaseFeedDisplayNode.h"

@interface _TtC6Reddit27AwardedCommentHighlightNode : BaseFeedDisplayNode
{
    // Error parsing type: , name: highlight
    // Error parsing type: , name: highlightColor
    // Error parsing type: , name: isBubbling
}

- (void).cxx_destruct;
- (id)initWithVisibilityTracker:(id)arg1 visibilityOptions:(id)arg2;
- (void)didExitFullyVisibleStateWithVisibilityContext:(id)arg1;
- (void)didEnterFullyVisibleStateWithVisibilityContext:(id)arg1;
- (void)didEnterVisibleState;
- (void)didLoad;
- (void)playBubbling;
- (void)setupWithHighlightType:(unsigned long long)arg1 color:(id)arg2;
- (id)init;

@end

