//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "UIViewControllerTransitioningDelegate-Protocol.h"

@protocol PostViewControllerDelegate;

@interface _TtC6Reddit22PostMenuViewController : UIViewController <UIViewControllerTransitioningDelegate>
{
    // Error parsing type: , name: delegate
    // Error parsing type: , name: accountContext
    // Error parsing type: , name: analyticBaseURL
    // Error parsing type: , name: availablePostTypes
    // Error parsing type: , name: subreddit
    // Error parsing type: , name: themeGuidance
    // Error parsing type: , name: videoPlayerManager
    // Error parsing type: , name: powerupsInfo
    // Error parsing type: , name: closeButton
    // Error parsing type: , name: collectionView
    // Error parsing type: , name: dimmerView
    // Error parsing type: , name: menuContainerView
    // Error parsing type: , name: titleLabel
}

- (void).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)close;
- (id)animationControllerForDismissedController:(id)arg1;
- (id)animationControllerForPresentedController:(id)arg1 presentingController:(id)arg2 sourceController:(id)arg3;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (_Bool)collectionView:(id)arg1 shouldSelectItemAtIndexPath:(id)arg2;
- (_Bool)collectionView:(id)arg1 shouldHighlightItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)mediaSelectionViewController:(id)arg1 didSelect:(id)arg2;
- (void)viewDidLoad;
@property(nonatomic) struct CGSize preferredContentSize;
@property(nonatomic, readonly) unsigned long long supportedInterfaceOrientations;
- (id)initWithCoder:(id)arg1;
- (id)initWithAccountContext:(id)arg1 analyticBaseURL:(id)arg2 subreddit:(id)arg3;
@property(nonatomic) __weak id <PostViewControllerDelegate> delegate; // @synthesize delegate;

@end

