//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BaseViewController.h"

@interface _TtC6Reddit26AnonymousBrowsingExitPopup : BaseViewController
{
    // Error parsing type: , name: anonymousModeManager
    // Error parsing type: , name: source
    // Error parsing type: , name: corneredView
    // Error parsing type: , name: scrollViewContainerView
    // Error parsing type: , name: scrollView
    // Error parsing type: , name: stackView
    // Error parsing type: , name: titleLabel
    // Error parsing type: , name: closeButton
    // Error parsing type: , name: descriptionContainerView
    // Error parsing type: , name: descriptionLabel
    // Error parsing type: , name: leaveAnonymousBrowsingButton
    // Error parsing type: , name: kUpdateSettingsURLString
}

- (void).cxx_destruct;
- (void)viewDidLoad;
- (id)initWithAnonymousModeManager:(id)arg1 source:(unsigned long long)arg2;
- (id)init;

@end

