//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC6Reddit26RedditCinemaViewController.h"

@interface _TtC6Reddit26RedditCinemaViewController (Reddit3)
- (void)collectionNode:(id)arg1 willBeginBatchFetchWithContext:(id)arg2;
- (_Bool)shouldBatchFetchForCollectionNode:(id)arg1;
- (void)collectionNode:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (CDUnknownBlockType)collectionNode:(id)arg1 nodeBlockForItemAtIndexPath:(id)arg2;
- (long long)collectionNode:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)numberOfSectionsInCollectionNode:(id)arg1;
@end

