//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIButton.h>

__attribute__((visibility("hidden")))
@interface _TtCC7Economy8Powerups14ProgressButton : UIButton
{
    // Error parsing type: , name: backgroundGradient
    // Error parsing type: , name: fillGradient
    // Error parsing type: , name: progress
}

- (void).cxx_destruct;
- (void)layoutSublayersOfLayer:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

