//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC6Reddit26SplashScreenViewController.h"

@interface _TtC6Reddit26SplashScreenViewController (Reddit1)
- (void)didTapDismissButtonWithRegistrationViewController:(id)arg1;
- (void)didTapLoginButtonWithRegistrationViewController:(id)arg1;
- (void)didAuthenticateServiceWithRegistrationViewController:(id)arg1 service:(id)arg2 isNewUser:(_Bool)arg3;
@end

