//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

__attribute__((visibility("hidden")))
@interface _TtCC7Economy8Powerups32LevelIndicatorCollectionViewCell : UICollectionViewCell
{
    // Error parsing type: , name: titleView
    // Error parsing type: , name: isUnlocked
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic) _Bool selected;
- (_Bool)isSelected;

@end

