//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtC12RedditWallet16WalletRepository : _TtCs12_SwiftObject
{
    // Error parsing type: , name: dataSource
    // Error parsing type: , name: communitiesRepository
    // Error parsing type: , name: userResponseRepository
    // Error parsing type: , name: transactionsRepository
    // Error parsing type: , name: subscriptionsRepository
    // Error parsing type: , name: subscriptions
}

@end

