//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC6Reddit27SearchAnalyticsEventFactory.h"

@interface _TtC6Reddit27SearchAnalyticsEventFactory (Reddit)
+ (id)searchClickPostEventWithPost:(id)arg1 railsContext:(id)arg2 isNSFWHidden:(_Bool)arg3 discoveryUnit:(id)arg4 postsPks:(id)arg5 position:(id)arg6 relativePosition:(id)arg7;
+ (id)searchClickPostEventWithPost:(id)arg1 railsContext:(id)arg2 isNSFWHidden:(_Bool)arg3 position:(id)arg4;
+ (id)searchViewPostEventWithPost:(id)arg1 railsContext:(id)arg2 isNSFWHidden:(_Bool)arg3 discoveryUnit:(id)arg4 postsPks:(id)arg5 position:(id)arg6 relativePosition:(id)arg7;
+ (id)searchViewPostEventWithPost:(id)arg1 railsContext:(id)arg2 isNSFWHidden:(_Bool)arg3 position:(id)arg4;
@end

