//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class UIImage, _TtC6Reddit28MediaSelectionViewController;

@protocol _TtP6Reddit36MediaSelectionViewControllerDelegate_
- (void)mediaSelectionViewController:(_TtC6Reddit28MediaSelectionViewController *)arg1 didSelect:(UIImage *)arg2;
@end

