//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Economy/NSObject-Protocol.h>

@class AccountManager, RedditService;
@protocol _TtP7Economy22EconomyAnalyticsLogger_;

@protocol _TtP7Economy25EconomyDependencyProvider_ <NSObject>
@property(nonatomic, readonly) _Bool inAppPurchaseSkipReceiptValidation;
@property(nonatomic, readonly) _Bool inAppPurchaseForceDeferredTransaction;
- (_Bool)isInAnonymousBrowsingWithRedditService:(RedditService *)arg1;
- (id <_TtP7Economy22EconomyAnalyticsLogger_>)economyAnalyticsLoggerWithRedditService:(RedditService *)arg1;
@property(nonatomic, readonly) AccountManager *accountManager;
@end

