//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Economy/NSObject-Protocol.h>

@class Award, NSString;

@protocol _TtP7Economy25AwardSelectionEventLogger_ <NSObject>
- (void)logClickEditOptionsEvent;
- (void)logCloseGiveAwardModalEvent;
- (void)logTypeMessageEvent;
- (void)logSelectAwardEventWithAward:(Award *)arg1 rowIndex:(long long)arg2 columnIndex:(long long)arg3 miniPillTag:(NSString *)arg4 miniPillText:(NSString *)arg5;
@end

