//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class _TtC7Economy19AwardSelectionState, _TtC7Economy21AwardSelectionOptions;

@protocol _TtP6Reddit22AwardSelectionDelegate_ <NSObject>
- (void)dismissForAwardSelectionWithOptions:(_TtC7Economy21AwardSelectionOptions *)arg1 state:(_TtC7Economy19AwardSelectionState *)arg2;
- (void)sendAwardForAwardSelectionWithOptions:(_TtC7Economy21AwardSelectionOptions *)arg1 state:(_TtC7Economy19AwardSelectionState *)arg2;
- (void)getCoinsForAwardSelectionWithOptions:(_TtC7Economy21AwardSelectionOptions *)arg1 state:(_TtC7Economy19AwardSelectionState *)arg2;
@end

