//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <RedditCore/NSURLRequestProcessor-Protocol.h>
#import <RedditCore/NSURLResponseProcessor-Protocol.h>

@class NSString, NSUserDefaults;

@interface AccountIdentifiers : NSObject <NSURLRequestProcessor, NSURLResponseProcessor>
{
    _Bool _isAnonymousBrowsing;
    NSUserDefaults *_userDefaults;
    NSString *_anonymousDeviceId;
    NSString *_anonymousReddaid;
}

+ (id)anonymousIdentifiersWithDeviceId:(id)arg1;
+ (id)standardIdentifiers;
- (void).cxx_destruct;
@property(retain, nonatomic) NSString *anonymousReddaid; // @synthesize anonymousReddaid=_anonymousReddaid;
@property(readonly, nonatomic) NSString *anonymousDeviceId; // @synthesize anonymousDeviceId=_anonymousDeviceId;
@property(readonly, nonatomic) NSUserDefaults *userDefaults; // @synthesize userDefaults=_userDefaults;
@property(readonly, nonatomic) _Bool isAnonymousBrowsing; // @synthesize isAnonymousBrowsing=_isAnonymousBrowsing;
- (void)updateReddaidWithResponse:(id)arg1;
- (void)processResponse:(id)arg1;
- (void)processRequest:(id)arg1;
@property(retain, nonatomic) NSString *reddaid;
@property(readonly, nonatomic) NSString *idfa;
@property(readonly, nonatomic) NSString *deviceId;
- (id)initWithUserDefaults:(id)arg1 anonymousDeviceId:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

