//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "PopupViewController.h"

@class NSArray;

@interface AlertPopupViewController : PopupViewController
{
    NSArray *_actions;
}

+ (id)blockUserPopupWithAccountContext:(id)arg1 source:(id)arg2 confirmAction:(CDUnknownBlockType)arg3;
- (void).cxx_destruct;
@property(copy, nonatomic) NSArray *actions; // @synthesize actions=_actions;
- (void)dismissAction;
- (id)initWithAccountContext:(id)arg1 title:(id)arg2 message:(id)arg3 bottomButtons:(id)arg4;
- (id)initWithAccountContext:(id)arg1 title:(id)arg2 message:(id)arg3 actions:(id)arg4;

@end

