//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <AnalyticsFramework/NSCoding-Protocol.h>
#import <AnalyticsFramework/NSCopying-Protocol.h>
#import <AnalyticsFramework/TBase-Protocol.h>

@class NSString;

@interface AnalyticsBroadcast : NSObject <TBase, NSCoding, NSCopying>
{
    _Bool _unique_watchersIsSet;
    _Bool _max_concurrent_watchersIsSet;
    long long _unique_watchers;
    long long _max_concurrent_watchers;
}

@property(nonatomic) _Bool max_concurrent_watchersIsSet; // @synthesize max_concurrent_watchersIsSet=_max_concurrent_watchersIsSet;
@property(nonatomic) long long max_concurrent_watchers; // @synthesize max_concurrent_watchers=_max_concurrent_watchers;
@property(nonatomic) _Bool unique_watchersIsSet; // @synthesize unique_watchersIsSet=_unique_watchersIsSet;
@property(nonatomic) long long unique_watchers; // @synthesize unique_watchers=_unique_watchers;
@property(readonly, copy) NSString *description;
- (_Bool)validate:(id *)arg1;
- (_Bool)write:(id)arg1 error:(id *)arg2;
- (_Bool)read:(id)arg1 error:(id *)arg2;
- (void)unsetMax_concurrent_watchers;
- (void)unsetUnique_watchers;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (_Bool)isEqual:(id)arg1;
@property(readonly) unsigned long long hash;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithUnique_watchers:(long long)arg1 max_concurrent_watchers:(long long)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

