//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "AnalyticsProcessorDelegate-Protocol.h"
#import "_TtP7Economy22EconomyAnalyticsLogger_-Protocol.h"

@class AnalyticsEventProcessor, NSString;

@interface AnalyticsManager : NSObject <_TtP7Economy22EconomyAnalyticsLogger_, AnalyticsProcessorDelegate>
{
    _Bool _enabled;
    AnalyticsEventProcessor *_eventProcessor;
}

+ (void)setup;
+ (id)instance;
- (void).cxx_destruct;
@property _Bool enabled; // @synthesize enabled=_enabled;
@property(readonly, nonatomic) AnalyticsEventProcessor *eventProcessor; // @synthesize eventProcessor=_eventProcessor;
- (void)persistInstallTimeStamp;
- (void)appBackgrounded;
- (void)logAnalyticsEvents:(id)arg1;
- (void)logAnalyticsEvent:(id)arg1;
- (void)configureWithBranchParameters:(id)arg1 isFirstLaunch:(_Bool)arg2;
- (void)enable;
- (id)init;
- (void)logLaunchEventWithReferringURL:(id)arg1 isFirstLaunch:(_Bool)arg2;
- (void)logWithEvents:(id)arg1;
- (void)logWithEvent:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

