//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "RootViewControllerDelegate-Protocol.h"

@class Account, MainTabBarController, NSString, NSURL, RedditService, RootViewController;
@protocol AccountContext;

@interface AppFlowCoordinator : NSObject <RootViewControllerDelegate>
{
    _Bool _didScheduleBranchURL;
    _Bool _isBranchMatchGuaranteed;
    id <AccountContext> _accountContext;
    RootViewController *_rootViewController;
    MainTabBarController *_mainTabController;
    NSURL *_scheduledURL;
    NSURL *_pendingEmailVerificationURL;
    NSURL *_pushNotifURLToHandleAfterAccountSwitching;
}

+ (id)instance;
- (void).cxx_destruct;
@property(copy, nonatomic) NSURL *pushNotifURLToHandleAfterAccountSwitching; // @synthesize pushNotifURLToHandleAfterAccountSwitching=_pushNotifURLToHandleAfterAccountSwitching;
@property(nonatomic) _Bool isBranchMatchGuaranteed; // @synthesize isBranchMatchGuaranteed=_isBranchMatchGuaranteed;
@property(nonatomic) _Bool didScheduleBranchURL; // @synthesize didScheduleBranchURL=_didScheduleBranchURL;
@property(copy, nonatomic) NSURL *pendingEmailVerificationURL; // @synthesize pendingEmailVerificationURL=_pendingEmailVerificationURL;
@property(copy, nonatomic) NSURL *scheduledURL; // @synthesize scheduledURL=_scheduledURL;
@property(retain, nonatomic) MainTabBarController *mainTabController; // @synthesize mainTabController=_mainTabController;
@property(readonly, nonatomic) RootViewController *rootViewController; // @synthesize rootViewController=_rootViewController;
@property(retain, nonatomic) id <AccountContext> accountContext; // @synthesize accountContext=_accountContext;
- (void)navigateToLoginCaptureView;
- (void)handleEmailVerificationURL:(id)arg1;
- (void)didChangeUser:(id)arg1;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)configureWithAccountContext:(id)arg1;
- (unsigned long long)pushNotificationPromptStyle;
- (void)showPushNotificationPromptIfNeededWithCompletion:(CDUnknownBlockType)arg1;
- (void)rootViewControllerDidInstallNewMainTabBar;
- (void)refreshConfig;
- (void)handlePushNotificationTappedNotification:(id)arg1;
- (id)extractDeeplinkURLFromPushNotification:(id)arg1;
- (void)cacheURLFromAppLaunchOptions:(id)arg1;
- (void)navigateToURLIfPossible:(id)arg1;
- (void)navigateToCachedURLIfPossible;
- (_Bool)canProcessBranchURLWithMatchGuaranteed:(_Bool)arg1;
- (void)scheduleNavigatingToURL:(id)arg1;
- (void)scheduleNavigatingToBranchURL:(id)arg1 isMatchGuaranteed:(_Bool)arg2;
- (id)init;
- (void)dealloc;
@property(readonly, nonatomic) RedditService *currentService;
@property(readonly, nonatomic) Account *currentAccount;
- (void)configureWithRootViewController:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

