//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <RedditUI/BaseView.h>

#import "PlayerViewDelegate-Protocol.h"

@class BaseLabel, ContentImageView, ContentVideoView, HlsPlayerView, NSString, RichTextAnimatedImageElement, RichTextImageElement, RichTextMediaBaseElement, RichTextVideoElement, _TtC6Reddit15RedditVideoNode;
@protocol AttributedLabelMediaDelegate, ViewContext;

@interface AttributedLabelMediaView : BaseView <PlayerViewDelegate>
{
    HlsPlayerView *_videoView;
    id <AttributedLabelMediaDelegate> _delegate;
    id <ViewContext> _viewContext;
    RichTextImageElement *_imageElement;
    RichTextAnimatedImageElement *_animatedImageElement;
    RichTextVideoElement *_videoElement;
    ContentImageView *_imageView;
    ContentVideoView *_animatedImageView;
    BaseLabel *_captionLabel;
    BaseLabel *_mediaStatusLabel;
    _TtC6Reddit15RedditVideoNode *_videoNode;
}

+ (struct CGSize)sizeForCaption:(id)arg1 withMaxWidth:(double)arg2;
+ (struct CGSize)sizeWithMediaSize:(struct CGSize)arg1 withMaxWidth:(double)arg2 withCaption:(id)arg3;
+ (struct CGSize)sizeWithElement:(id)arg1 withMaxWidth:(double)arg2;
- (void).cxx_destruct;
@property(retain, nonatomic) _TtC6Reddit15RedditVideoNode *videoNode; // @synthesize videoNode=_videoNode;
@property(retain, nonatomic) BaseLabel *mediaStatusLabel; // @synthesize mediaStatusLabel=_mediaStatusLabel;
@property(retain, nonatomic) BaseLabel *captionLabel; // @synthesize captionLabel=_captionLabel;
@property(retain, nonatomic) ContentVideoView *animatedImageView; // @synthesize animatedImageView=_animatedImageView;
@property(retain, nonatomic) ContentImageView *imageView; // @synthesize imageView=_imageView;
@property(retain, nonatomic) RichTextVideoElement *videoElement; // @synthesize videoElement=_videoElement;
@property(retain, nonatomic) RichTextAnimatedImageElement *animatedImageElement; // @synthesize animatedImageElement=_animatedImageElement;
@property(retain, nonatomic) RichTextImageElement *imageElement; // @synthesize imageElement=_imageElement;
@property(readonly, nonatomic) id <ViewContext> viewContext; // @synthesize viewContext=_viewContext;
@property(nonatomic) __weak id <AttributedLabelMediaDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) HlsPlayerView *videoView; // @synthesize videoView=_videoView;
- (_Bool)shouldDisableAutoplay;
- (void)playerViewDidEndPlaying:(id)arg1;
- (void)playerViewDidBeginPlaying:(id)arg1;
@property(readonly, nonatomic) RichTextMediaBaseElement *mediaElement;
- (struct CGSize)sizeForMediaWithMaxWidth:(double)arg1 withCaption:(_Bool)arg2;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)removeFromSuperview;
- (void)didTapMediaView:(id)arg1;
- (void)addSupplementalViewsForElement:(id)arg1;
- (id)initWithViewContext:(id)arg1 videoElement:(id)arg2;
- (void)addTapRecognizerToMediaView:(id)arg1;
- (id)initWithViewContext:(id)arg1 animatedImageElement:(id)arg2;
- (id)initWithViewContext:(id)arg1 imageElement:(id)arg2;
- (id)initWithViewContext:(id)arg1 element:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

