//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSTimer;

@interface AudioManager : NSObject
{
    _Bool _audioSessionActive;
    _Bool _thirdPartyAudioIsPlaying;
    _Bool _thirdPartyAudioWasSilenced;
    _Bool _isRedditVideoV2Enabled;
    _Bool _shouldForceSessionUpdateOnNextActivation;
    long long _numberOfAudioSessionsActive;
    NSTimer *_audioDeactivationTimer;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
@property(nonatomic) _Bool shouldForceSessionUpdateOnNextActivation; // @synthesize shouldForceSessionUpdateOnNextActivation=_shouldForceSessionUpdateOnNextActivation;
@property(nonatomic) _Bool isRedditVideoV2Enabled; // @synthesize isRedditVideoV2Enabled=_isRedditVideoV2Enabled;
@property(nonatomic) _Bool thirdPartyAudioWasSilenced; // @synthesize thirdPartyAudioWasSilenced=_thirdPartyAudioWasSilenced;
@property(nonatomic) _Bool thirdPartyAudioIsPlaying; // @synthesize thirdPartyAudioIsPlaying=_thirdPartyAudioIsPlaying;
@property(retain, nonatomic) NSTimer *audioDeactivationTimer; // @synthesize audioDeactivationTimer=_audioDeactivationTimer;
@property(nonatomic) long long numberOfAudioSessionsActive; // @synthesize numberOfAudioSessionsActive=_numberOfAudioSessionsActive;
@property(nonatomic) _Bool audioSessionActive; // @synthesize audioSessionActive=_audioSessionActive;
- (void)activateAudioSession;
- (void)deactivateAudioSession;
- (void)tryDeactivateAudioSession;
- (void)volumeButtonObserverDidStopObserving;
- (void)handleAppDidEnterBackground;
- (void)handleAppDidEnterForeground;
- (void)experimentsDidFetch:(id)arg1;
- (id)init;
- (void)dealloc;

@end

