//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "AwardCoordinatorDelegate-Protocol.h"
#import "SelectAwardEditOptionsViewControllerDelegate-Protocol.h"

@class AwardCoordinatorV2, GildingEventLogger, NSString, _TtCC7Economy8Awarding6FlowV2;
@protocol AccountContext, _TtP6Reddit20AwardingFlowDelegate_;

@interface AwardingFlow : NSObject <AwardCoordinatorDelegate, SelectAwardEditOptionsViewControllerDelegate>
{
    // Error parsing type: , name: awardable
    // Error parsing type: , name: accountContext
    // Error parsing type: , name: correlationId
    // Error parsing type: , name: awardCoordinator
    // Error parsing type: , name: eventLogger
    // Error parsing type: , name: flowV2
    // Error parsing type: , name: delegate
    // Error parsing type: , name: keepAliveInstance
    // Error parsing type: , name: onChangeOfEditOptions
}

- (void).cxx_destruct;
- (id)init;
- (void)editOptionsViewControllerDidTypeMessage:(id)arg1;
- (void)editOptionsViewController:(id)arg1 didToggleAnonymous:(_Bool)arg2;
- (void)editOptionsViewController:(id)arg1 didSaveOptions:(id)arg2;
- (void)sendAwardWithOptions:(id)arg1 award:(id)arg2 isAnonymous:(_Bool)arg3 message:(id)arg4 hostViewController:(id)arg5;
- (id)getMoreCoinsViewController;
- (void)setIsAnonymousByDefaultWithIsAnonymousByDefault:(_Bool)arg1;
- (_Bool)isAnonymousByDefault;
- (void)presentErrorWithRedditDomainError:(id)arg1;
- (void)awardCoordinator:(id)arg1 didChangeProcessing:(_Bool)arg2;
- (void)awardCoordinatorDidFail:(id)arg1;
- (void)awardCoordinatorDidFinish:(id)arg1;
- (void)awardCoordinatorDidStart:(id)arg1;
- (void)startFromViewController:(id)arg1 config:(id)arg2;
- (id)initWithComment:(id)arg1 parentPost:(id)arg2 accountContext:(id)arg3 correlationId:(id)arg4;
- (id)initWithLiveStreamPost:(id)arg1 liveStream:(id)arg2 accountContext:(id)arg3 correlationId:(id)arg4;
- (id)initWithPost:(id)arg1 accountContext:(id)arg2 correlationId:(id)arg3;
@property(nonatomic) __weak id <_TtP6Reddit20AwardingFlowDelegate_> delegate; // @synthesize delegate;
@property(nonatomic, retain) _TtCC7Economy8Awarding6FlowV2 *flowV2; // @synthesize flowV2;
@property(nonatomic, retain) GildingEventLogger *eventLogger; // @synthesize eventLogger;
@property(nonatomic, retain) AwardCoordinatorV2 *awardCoordinator; // @synthesize awardCoordinator;
@property(nonatomic, readonly) NSString *correlationId;
@property(nonatomic, readonly) id <AccountContext> accountContext; // @synthesize accountContext;

@end

