//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class Award, AwardDetailsEventLogger, Comment, NSString, NSURL, Post, Subreddit;
@protocol AccountContext;

@protocol AwardDetailsNavigatable <NSObject>
- (void)showHideConfirmationDialogWithAccountContext:(id <AccountContext>)arg1 award:(Award *)arg2 awardedTarget:(NSString *)arg3 isAuthor:(_Bool)arg4 eventLogger:(AwardDetailsEventLogger *)arg5 completion:(void (^)(void))arg6;
- (void)showReportConfirmationDialogWithAccountContext:(id <AccountContext>)arg1 award:(Award *)arg2 completion:(void (^)(void))arg3;
- (void)showAwardInfoWithAccountContext:(id <AccountContext>)arg1 award:(Award *)arg2 gildingTarget:(unsigned long long)arg3 subreddit:(Subreddit *)arg4;
- (void)showSelectAwardScreenForComment:(Comment *)arg1 parentPost:(Post *)arg2 accountContext:(id <AccountContext>)arg3 correlationId:(NSString *)arg4;
- (void)showSelectAwardScreenForPost:(Post *)arg1 accountContext:(id <AccountContext>)arg2 correlationId:(NSString *)arg3;
- (void)showWebPageWithURL:(NSURL *)arg1 accountContext:(id <AccountContext>)arg2;
- (void)close;
@end

