//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIResponder.h>

#import "AwardCoordinator-Protocol.h"
#import "PurchaseAwardCoordinatorDelegate-Protocol.h"
#import "SelectAwardEditOptionsViewControllerDelegate-Protocol.h"
#import "SelectAwardViewControllerDelegate-Protocol.h"
#import "_TtP6Reddit22AwardSelectionDelegate_-Protocol.h"

@class Comment, GildingEventLogger, GoldProduct, NSNumber, NSString, Post, PurchaseAwardCoordinator, UIViewController, _TtC6Reddit24CoinMarketingEventLogger, _TtC6Reddit25GildingPurchaseController, _TtC6Reddit34GoldUpsellImagePopupViewController, _TtC7Economy19AwardSelectionState, _TtC7Economy21AwardSelectionOptions;
@protocol AccountContext, AwardCoordinatorDelegate;

@interface AwardCoordinatorV2 : UIResponder <SelectAwardViewControllerDelegate, SelectAwardEditOptionsViewControllerDelegate, PurchaseAwardCoordinatorDelegate, _TtP6Reddit22AwardSelectionDelegate_, AwardCoordinator>
{
    id <AwardCoordinatorDelegate> _delegate;
    id <AccountContext> _accountContext;
    _TtC7Economy19AwardSelectionState *_state;
    Post *_post;
    Comment *_comment;
    NSString *_correlationId;
    unsigned long long _gildingTarget;
    NSNumber *_isAwardPurchased;
    CDUnknownBlockType _makeAwardSelectionViewControllerV2;
    UIViewController *_fromViewController;
    UIViewController *_selectAwardViewController;
    PurchaseAwardCoordinator *_purchaseAwardCoordinator;
    GildingEventLogger *_eventLogger;
    NSString *_previousLastGivenAwardIdentifier;
    _TtC6Reddit34GoldUpsellImagePopupViewController *_goldUpsellImagePopupViewController;
    _TtC6Reddit25GildingPurchaseController *_gildPurchaseController;
    _TtC6Reddit24CoinMarketingEventLogger *_coinMarketingEventLogger;
    _TtC7Economy21AwardSelectionOptions *_options;
    GoldProduct *_lowCoinOfferProduct;
}

@property(nonatomic) __weak GoldProduct *lowCoinOfferProduct; // @synthesize lowCoinOfferProduct=_lowCoinOfferProduct;
@property(copy, nonatomic) _TtC7Economy21AwardSelectionOptions *options; // @synthesize options=_options;
@property(retain, nonatomic) _TtC6Reddit24CoinMarketingEventLogger *coinMarketingEventLogger; // @synthesize coinMarketingEventLogger=_coinMarketingEventLogger;
@property(retain, nonatomic) _TtC6Reddit25GildingPurchaseController *gildPurchaseController; // @synthesize gildPurchaseController=_gildPurchaseController;
@property(retain, nonatomic) _TtC6Reddit34GoldUpsellImagePopupViewController *goldUpsellImagePopupViewController; // @synthesize goldUpsellImagePopupViewController=_goldUpsellImagePopupViewController;
@property(retain, nonatomic) NSString *previousLastGivenAwardIdentifier; // @synthesize previousLastGivenAwardIdentifier=_previousLastGivenAwardIdentifier;
@property(retain, nonatomic) GildingEventLogger *eventLogger; // @synthesize eventLogger=_eventLogger;
@property(retain, nonatomic) PurchaseAwardCoordinator *purchaseAwardCoordinator; // @synthesize purchaseAwardCoordinator=_purchaseAwardCoordinator;
@property(retain, nonatomic) UIViewController *selectAwardViewController; // @synthesize selectAwardViewController=_selectAwardViewController;
@property(nonatomic) __weak UIViewController *fromViewController; // @synthesize fromViewController=_fromViewController;
@property(readonly, nonatomic) CDUnknownBlockType makeAwardSelectionViewControllerV2; // @synthesize makeAwardSelectionViewControllerV2=_makeAwardSelectionViewControllerV2;
@property(retain, nonatomic) NSNumber *isAwardPurchased; // @synthesize isAwardPurchased=_isAwardPurchased;
@property(nonatomic) unsigned long long gildingTarget; // @synthesize gildingTarget=_gildingTarget;
@property(retain, nonatomic) NSString *correlationId; // @synthesize correlationId=_correlationId;
@property(retain, nonatomic) Comment *comment; // @synthesize comment=_comment;
@property(retain, nonatomic) Post *post; // @synthesize post=_post;
@property(retain, nonatomic) _TtC7Economy19AwardSelectionState *state; // @synthesize state=_state;
@property(readonly, nonatomic) id <AccountContext> accountContext; // @synthesize accountContext=_accountContext;
@property(nonatomic) __weak id <AwardCoordinatorDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)showGoldUpsell;
- (void)checkForGoldUpsell;
- (void)purchaseLowCoinOffer;
- (void)dismissForAwardSelectionWithOptions:(id)arg1 state:(id)arg2;
- (void)sendAwardForAwardSelectionWithOptions:(id)arg1 state:(id)arg2;
- (void)getCoinsForAwardSelectionWithOptions:(id)arg1 state:(id)arg2;
- (void)purchaseAwardCoordinatorDidCancel:(id)arg1;
- (void)purchaseAwardCoordinatorDidFail:(id)arg1;
- (void)purchaseAwardCoordinator:(id)arg1 didSucceedWithDeferredStatus:(_Bool)arg2;
- (void)editOptionsViewControllerDidTypeMessage:(id)arg1;
- (void)editOptionsViewController:(id)arg1 didToggleAnonymous:(_Bool)arg2;
- (void)editOptionsViewController:(id)arg1 didSaveOptions:(id)arg2;
- (void)selectAwardViewControllerDidTapGetCoinsButton:(id)arg1;
- (void)selectAwardViewControllerDidTapCloseButton:(id)arg1;
- (void)selectAwardViewControllerDidTapActionButton:(id)arg1;
- (void)selectAwardViewControllerDidTapEditOptionsButton:(id)arg1;
- (void)selectAwardViewControllerDidTapInfoButton:(id)arg1;
- (void)presentGetCoinsInViewController:(id)arg1;
- (void)dismissAwardSelection;
- (void)sendAward;
- (void)restorePreviousLastGivenAwardIdentifier;
- (void)handleGildingCompletionWithError:(id)arg1;
- (void)optimisticallyUpdateGivenAwardsCache;
- (void)submitAward;
- (void)startCoinPurchaseFlow;
- (void)directToPremiumMarketing;
- (void)showEditOptionsScreen;
- (void)showAwardsHelpPage;
- (void)showSelectAward;
- (void)dismissSelectAwardViewControllerWithCompletion:(CDUnknownBlockType)arg1 dismissalReason:(unsigned long long)arg2;
- (void)startFromViewController:(id)arg1 config:(id)arg2;
- (_Bool)useAwardingTrayV2ForRPAN:(_Bool)arg1;
- (id)initWithComment:(id)arg1 parentPost:(id)arg2 accountContext:(id)arg3 correlationId:(id)arg4;
- (id)initWithPost:(id)arg1 stream:(id)arg2 accountContext:(id)arg3 correlationId:(id)arg4;
- (id)initWithPost:(id)arg1 accountContext:(id)arg2 correlationId:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

