//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <RedditCore/Award.h>

@class NSURL;

@interface Award (Economy)
+ (struct CGSize)iconSize:(long long)arg1;
- (id)awardIconURLWithSize:(long long)arg1;
@property(nonatomic, readonly) NSURL *liveStreamChatAwardImageURL;
@property(nonatomic, readonly) NSURL *actionBarAwardImageURL;
@property(nonatomic, readonly) NSURL *giveAwardCoinPurchaseConfirmationImageURL;
@property(nonatomic, readonly) NSURL *giveAwardDescriptionImageURL;
@property(nonatomic, readonly) NSURL *giveAwardImageURL;
@property(nonatomic, readonly) NSURL *awardDetailsImageURL;
- (long long)RPANUIConfigurationTypeWithNewUIEnabled:(_Bool)arg1;
@end

