//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BaseFeedDisplayNode.h"

#import "_TtP6Reddit28HighlightableContentProtocol_-Protocol.h"

@class ChatPostContentNode, CommentTreeNode, _TtC6Reddit27ChatPostBlockedMessagesNode;

@interface ChatPostDisplayNode : BaseFeedDisplayNode <_TtP6Reddit28HighlightableContentProtocol_>
{
    CommentTreeNode *_commentNode;
    ChatPostContentNode *_contentNode;
    _TtC6Reddit27ChatPostBlockedMessagesNode *_blockedMessagesNode;
}

- (void).cxx_destruct;
@property(retain, nonatomic) _TtC6Reddit27ChatPostBlockedMessagesNode *blockedMessagesNode; // @synthesize blockedMessagesNode=_blockedMessagesNode;
@property(retain, nonatomic) ChatPostContentNode *contentNode; // @synthesize contentNode=_contentNode;
@property(retain, nonatomic) CommentTreeNode *commentNode; // @synthesize commentNode=_commentNode;
- (void)unhighlightContent;
- (void)highlightContentWithColor:(id)arg1;
- (id)layoutSpecThatFits:(CDStruct_90e057aa)arg1;
- (id)initWithBlockedMessagesBucket:(id)arg1 delegate:(id)arg2;
- (id)initWithViewContext:(id)arg1 subredditMentionsHandler:(id)arg2 commentNode:(id)arg3 options:(id)arg4 delegate:(id)arg5 isReplyFeatureEnabled:(_Bool)arg6 shouldShowVotingNodeBlock:(CDUnknownBlockType)arg7 shouldShowDownvote:(_Bool)arg8;

@end

