//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BaseFeedDisplayNode.h"

@class ChatPostContentNode, CommentTreeNode, _TtC6Reddit27ChatPostBlockedMessagesNode;

@interface ChatPostDisplayNode : BaseFeedDisplayNode
{
    CommentTreeNode *_commentNode;
    ChatPostContentNode *_contentNode;
    _TtC6Reddit27ChatPostBlockedMessagesNode *_blockedMessagesNode;
}

- (void).cxx_destruct;
@property(retain, nonatomic) _TtC6Reddit27ChatPostBlockedMessagesNode *blockedMessagesNode; // @synthesize blockedMessagesNode=_blockedMessagesNode;
@property(retain, nonatomic) ChatPostContentNode *contentNode; // @synthesize contentNode=_contentNode;
@property(retain, nonatomic) CommentTreeNode *commentNode; // @synthesize commentNode=_commentNode;
- (id)layoutSpecThatFits:(CDStruct_90e057aa)arg1;
- (id)initWithBlockedMessagesBucket:(id)arg1 delegate:(id)arg2;
- (id)initWithViewContext:(id)arg1 commentNode:(id)arg2 options:(id)arg3 delegate:(id)arg4 isReplyFeatureEnabled:(_Bool)arg5 shouldShowVotingNodeBlock:(CDUnknownBlockType)arg6 shouldShowDownvote:(_Bool)arg7;

@end

