//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <RedditCore/Comment.h>

@interface Comment (CommunityAwards)
+ (id)highlightColorForType:(unsigned long long)arg1;
- (_Bool)isLastGivenAward:(id)arg1 forGivenAwardsManager:(id)arg2;
@property(readonly, nonatomic) _Bool shouldHighlightForHighAward;
@property(readonly, nonatomic) unsigned long long awardHighlight;
- (_Bool)hasBeenAwardedByCurrentAccountWithGivenAwardsManager:(id)arg1;
- (id)orderedAwardingTotalsWithFirstModAwardRemovedWithGivenAwardsManager:(id)arg1;
- (id)firstModeratorAwardingTotalWithGivenAwardsManager:(id)arg1;
- (id)orderedAwardingTotalsWithGivenAwardsManager:(id)arg1;
@end

