//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BaseCollectionViewCellNode.h"

@class ASButtonNode, ASDisplayNode, ASTextNode, AdPost, FeedPostOptions, FeedPostThumbnailNode, FeedPostTitleNode;
@protocol CommentAdPostCellNodeDelegate, ViewContext;

@interface CommentAdPostCellNode : BaseCollectionViewCellNode
{
    AdPost *_post;
    id <ViewContext> _viewContext;
    id <CommentAdPostCellNodeDelegate> _delegate;
    FeedPostOptions *_options;
    ASDisplayNode *_spacer;
    FeedPostTitleNode *_titleNode;
    ASTextNode *_textNode;
    ASTextNode *_urlNode;
    FeedPostThumbnailNode *_thumbnailNode;
    ASButtonNode *_commentNode;
    ASButtonNode *_buttonNode;
}

- (void).cxx_destruct;
@property(retain, nonatomic) ASButtonNode *buttonNode; // @synthesize buttonNode=_buttonNode;
@property(retain, nonatomic) ASButtonNode *commentNode; // @synthesize commentNode=_commentNode;
@property(retain, nonatomic) FeedPostThumbnailNode *thumbnailNode; // @synthesize thumbnailNode=_thumbnailNode;
@property(retain, nonatomic) ASTextNode *urlNode; // @synthesize urlNode=_urlNode;
@property(retain, nonatomic) ASTextNode *textNode; // @synthesize textNode=_textNode;
@property(retain, nonatomic) FeedPostTitleNode *titleNode; // @synthesize titleNode=_titleNode;
@property(retain, nonatomic) ASDisplayNode *spacer; // @synthesize spacer=_spacer;
@property(retain, nonatomic) FeedPostOptions *options; // @synthesize options=_options;
@property(nonatomic) __weak id <CommentAdPostCellNodeDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) id <ViewContext> viewContext; // @synthesize viewContext=_viewContext;
@property(readonly, nonatomic) AdPost *post; // @synthesize post=_post;
- (void)didChangeVisibilityWithContext:(id)arg1;
- (void)beginVisibilityTracking;
- (void)buttonNodeDidTap:(id)arg1;
- (void)commentNodeDidTap:(id)arg1;
- (void)thumbnailDidTap:(id)arg1;
- (void)textNodeDidTap:(id)arg1;
- (void)didTapDiscussion;
- (void)didTapContent;
- (void)configureNodes;
- (id)layoutSpecThatFits:(CDStruct_90e057aa)arg1;
- (void)didLoad;
- (id)initWithViewContext:(id)arg1 adPost:(id)arg2 delegate:(id)arg3;

@end

