//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BaseFeedDisplayNode.h"

#import "ASTextNodeDelegate-Protocol.h"
#import "ObjectObserverProtocol-Protocol.h"

@class ASDisplayNode, CommentMetaViewModel, CommentTreeAwardsNode, CommentTreeHeaderNode, CommentTreeLoadMoreView, CommentTreeNode, CommentTreeNodeOptions, CommentTreeTextNode, NSString, StructuredStyle, SubredditMentionsHandler, _TtC6Reddit26AwardBubblingHighlightNode;
@protocol AccountContext, CommentTreeContentNodeDelegate;

@interface CommentTreeContentNode : BaseFeedDisplayNode <ASTextNodeDelegate, ObjectObserverProtocol>
{
    CommentTreeTextNode *_textNode;
    id <AccountContext> _accountContext;
    CommentTreeNode *_commentNode;
    CommentMetaViewModel *_commentMetaViewModel;
    StructuredStyle *_subredditStyling;
    id <CommentTreeContentNodeDelegate> _delegate;
    CommentTreeNodeOptions *_commentOptions;
    CommentTreeLoadMoreView *_loadMoreView;
    CommentTreeHeaderNode *_headerNode;
    CommentTreeAwardsNode *_awardsNode;
    ASDisplayNode *_roundedHighlightNode;
    ASDisplayNode *_loadMoreNode;
    ASDisplayNode *_commandNode;
    _TtC6Reddit26AwardBubblingHighlightNode *_awardHighlightNode;
    unsigned long long _awardHighlight;
    SubredditMentionsHandler *_subredditMentionsHandler;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) SubredditMentionsHandler *subredditMentionsHandler; // @synthesize subredditMentionsHandler=_subredditMentionsHandler;
@property(nonatomic) unsigned long long awardHighlight; // @synthesize awardHighlight=_awardHighlight;
@property(retain, nonatomic) _TtC6Reddit26AwardBubblingHighlightNode *awardHighlightNode; // @synthesize awardHighlightNode=_awardHighlightNode;
@property(retain, nonatomic) ASDisplayNode *commandNode; // @synthesize commandNode=_commandNode;
@property(retain, nonatomic) ASDisplayNode *loadMoreNode; // @synthesize loadMoreNode=_loadMoreNode;
@property(retain, nonatomic) ASDisplayNode *roundedHighlightNode; // @synthesize roundedHighlightNode=_roundedHighlightNode;
@property(retain, nonatomic) CommentTreeAwardsNode *awardsNode; // @synthesize awardsNode=_awardsNode;
@property(retain, nonatomic) CommentTreeHeaderNode *headerNode; // @synthesize headerNode=_headerNode;
@property(retain, nonatomic) CommentTreeLoadMoreView *loadMoreView; // @synthesize loadMoreView=_loadMoreView;
@property(retain, nonatomic) CommentTreeNodeOptions *commentOptions; // @synthesize commentOptions=_commentOptions;
@property(nonatomic) __weak id <CommentTreeContentNodeDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) StructuredStyle *subredditStyling; // @synthesize subredditStyling=_subredditStyling;
@property(retain, nonatomic) CommentMetaViewModel *commentMetaViewModel; // @synthesize commentMetaViewModel=_commentMetaViewModel;
@property(retain, nonatomic) CommentTreeNode *commentNode; // @synthesize commentNode=_commentNode;
@property(readonly, nonatomic) id <AccountContext> accountContext; // @synthesize accountContext=_accountContext;
@property(retain, nonatomic) CommentTreeTextNode *textNode; // @synthesize textNode=_textNode;
- (void)setColorToHighlightView:(id)arg1;
- (void)updateAwardsHighlight;
- (void)resetBackgroundColors;
- (void)setBackgroundColors:(id)arg1;
- (id)layoutSpecThatFits:(CDStruct_90e057aa)arg1;
- (void)createLoadMoreNode;
- (void)createCommandNode;
- (void)createTextNode;
- (void)createAwardsNodeIfNecessary;
- (void)createHeaderNode;
- (void)createHighlightNode;
- (void)configureNodes;
- (void)configureAwardHighlightNode;
- (id)initWithAccountContext:(id)arg1 commentNode:(id)arg2 commentMetaViewModel:(id)arg3 subredditMentionsHandler:(id)arg4 styling:(id)arg5 delegate:(id)arg6 commentOptions:(id)arg7;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

