//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <RedditCore/Comment.h>

@class AwardingTotal, NSArray, UIColor;

@interface Comment (CommunityAwards)
+ (id)defaultAttributesUsingTheme:(id)arg1;
+ (id)activeLinkAttributesUsingTheme:(id)arg1;
+ (id)linkAttributesUsingTheme:(id)arg1;
- (_Bool)isLastGivenAward:(id)arg1;
- (_Bool)highlightForHighAwardWithSpecialHighlightingEnabled:(_Bool)arg1;
- (_Bool)shouldHighlightForHighAward;
@property(readonly, nonatomic) UIColor *awardHighlightColor;
@property(readonly, nonatomic) unsigned long long awardHighlight;
@property(readonly, nonatomic) _Bool hasBeenAwardedByCurrentAccount;
@property(readonly, nonatomic) NSArray *orderedAwardingTotalsWithFirstModAwardRemoved;
@property(readonly, nonatomic) AwardingTotal *firstModeratorAwardingTotal;
@property(readonly, nonatomic) NSArray *orderedAwardingTotals;
- (id)commentListMetadataUsingTheme:(id)arg1 shouldShowSubredditName:(_Bool)arg2;
- (id)commentModIconsStringUsingTheme:(id)arg1 shouldShowLockButton:(_Bool)arg2;
- (id)commentBodyStringForLinks:(id)arg1 withActiveLink:(id)arg2 usingTheme:(id)arg3;
- (id)cakeIconAttachmentUsingTheme:(id)arg1;
- (id)userIconsForData:(id)arg1 usingTheme:(id)arg2;
- (id)textAttachmentWithImageNamed:(id)arg1 usingTheme:(id)arg2;
- (id)headerTitleColorWithUserProvidedColor:(id)arg1 usingTheme:(id)arg2;
- (id)commentHeaderString:(_Bool)arg1 usingTheme:(id)arg2 shouldShowAuthorFlair:(_Bool)arg3 shouldBoldAuthorName:(_Bool)arg4 shouldShowCrowdControlLabel:(_Bool)arg5 usernameDecoration:(id)arg6 richTextLoader:(id)arg7 imagesLoaded:(CDUnknownBlockType)arg8;
@end

