//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "ReportViewControllerDataSource-Protocol.h"

@class Channel, Contact, NSString, RedditService;

@interface ContactKickDataSource : NSObject <ReportViewControllerDataSource>
{
    NSString *_selectedDuration;
    Contact *_contact;
    Channel *_channel;
    RedditService *_service;
}

@property(readonly, nonatomic) RedditService *service; // @synthesize service=_service;
@property(retain, nonatomic) Channel *channel; // @synthesize channel=_channel;
@property(retain, nonatomic) Contact *contact; // @synthesize contact=_contact;
@property(copy, nonatomic) NSString *selectedDuration; // @synthesize selectedDuration=_selectedDuration;
- (void).cxx_destruct;
- (void)submitReportWithItem:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)reportingSubject;
- (id)actionButtonTitle;
- (id)reportItems;
- (id)title;
- (id)initWithService:(id)arg1 contact:(id)arg2 channel:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

