//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <RedditCore/LegacyKeychainAdapter-Protocol.h>

@class NSMutableDictionary, NSString;

@interface EphemeralLegacyKeychainAdapter : NSObject <LegacyKeychainAdapter>
{
    NSString *_identifier;
    NSMutableDictionary *_data;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) NSMutableDictionary *data; // @synthesize data=_data;
@property(readonly, copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (_Bool)removeAllObjects;
- (_Bool)setString:(id)arg1 forKey:(id)arg2;
- (id)stringForKey:(id)arg1;
- (id)initWithIdentifier:(id)arg1 data:(id)arg2;
- (id)initWithIdentifier:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

