//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <RedditCore/ExperimentManager.h>

@interface ExperimentManager (Economy)
@property(nonatomic, readonly) _Bool isEconAwardsPlaqueEnabled;
@property(nonatomic, readonly) _Bool isEconCommentHighlightingEnabled;
@property(nonatomic, readonly) _Bool isEconFeedAwardsV2SheetEnabled;
@property(nonatomic, readonly) _Bool isEconRPANAwardsV2SheetEnabled;
@end

