//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <RedditCore/ExperimentManager.h>

@interface ExperimentManager (Economy)
@property(nonatomic, readonly) _Bool isLapsedUserTargetedOfferEnabled;
@property(nonatomic, readonly) _Bool isNewUserTargetedOfferEnabled;
@property(nonatomic, readonly) _Bool isPremiumFlowTestingEnabled;
@property(nonatomic, readonly) _Bool isEconSubredditPowerupsFullEnabled;
@property(nonatomic, readonly) _Bool isEconSubredditPowerupsEnabled;
@property(nonatomic, readonly) _Bool isEconCancelPremiumOfferEnabled;
@property(nonatomic, readonly) _Bool isEconKarmaAwardScoreEnabled;
@property(nonatomic, readonly) _Bool isEconFeedAwardTrayV2Enabled;
@property(nonatomic, readonly) _Bool isEconRPANAwardTrayV2Enabled;
- (void)exposeEconLoggedOutAwardingExperiement;
@property(nonatomic, readonly) _Bool isEconLoggedOutAwardingEnabled;
- (void)exposeEconAwardsPlaqueExperiement;
@property(nonatomic, readonly) _Bool isEconAwardsPlaqueEnabled;
@property(nonatomic, readonly) _Bool isEconDailyStorefrontClaimEnabled;
@property(nonatomic, readonly) _Bool isEconFeedAwardsV2SheetEnabled;
@property(nonatomic, readonly) _Bool isEconRPANAwardsV2SheetEnabled;
@property(nonatomic, readonly) _Bool isEconCommentHighlightingAnimationEnabled;
@property(nonatomic, readonly) _Bool isEconGiveAwardAnimationEnabled;
@property(nonatomic, readonly) _Bool isEconCommentHighlightingEnabled;
@end

