//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "DataProvider-Protocol.h"

@class Announcement, LiveEvent, NSString, RedditService, _TtC6Reddit22AnnouncementsViewModel;

@interface FeaturedLiveEventAndAnnouncementDataProvider : NSObject <DataProvider>
{
    _Bool _isAnnouncementV2Enabled;
    RedditService *_service;
    LiveEvent *_featuredLiveEvent;
    Announcement *_featuredAnnouncement;
    _TtC6Reddit22AnnouncementsViewModel *_announcementsViewModel;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool isAnnouncementV2Enabled; // @synthesize isAnnouncementV2Enabled=_isAnnouncementV2Enabled;
@property(retain, nonatomic) _TtC6Reddit22AnnouncementsViewModel *announcementsViewModel; // @synthesize announcementsViewModel=_announcementsViewModel;
@property(retain, nonatomic) Announcement *featuredAnnouncement; // @synthesize featuredAnnouncement=_featuredAnnouncement;
@property(retain, nonatomic) LiveEvent *featuredLiveEvent; // @synthesize featuredLiveEvent=_featuredLiveEvent;
@property(readonly, nonatomic) RedditService *service; // @synthesize service=_service;
- (void)invalidate;
- (id)processObjects:(id)arg1 currentCount:(long long)arg2;
- (void)fetchFromCurrentObjects:(id)arg1 fetchingMore:(_Bool)arg2 pageSize:(long long)arg3 completion:(CDUnknownBlockType)arg4;
- (id)initWithService:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

