//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AsyncDisplayKit/ASDisplayNode.h>

@class FeedPostHlsVideoView, FeedPostOptions, Post;
@protocol FeedPostHlsVideoViewDelegate;

@interface FeedPostHlsVideoNode : ASDisplayNode
{
    Post *_post;
    ASDisplayNode *_hlsVideoViewContainerNode;
    id <FeedPostHlsVideoViewDelegate> _delegate;
    Post *_crossPost;
    FeedPostOptions *_options;
}

- (void).cxx_destruct;
@property(nonatomic) __weak FeedPostOptions *options; // @synthesize options=_options;
@property(nonatomic) __weak Post *crossPost; // @synthesize crossPost=_crossPost;
@property(nonatomic) __weak id <FeedPostHlsVideoViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) ASDisplayNode *hlsVideoViewContainerNode; // @synthesize hlsVideoViewContainerNode=_hlsVideoViewContainerNode;
@property(readonly, nonatomic) Post *post; // @synthesize post=_post;
- (void)didBecomeFullyVisible;
- (void)noLongerPastVisibilityThreshold;
- (void)didPassVisibilityThreshold;
- (id)layoutSpecThatFits:(CDStruct_90e057aa)arg1;
- (void)didExitVisibleState;
- (void)didEnterVisibleState;
- (void)didExitPreloadState;
@property(readonly, nonatomic) FeedPostHlsVideoView *hlsVideoView;
- (id)initWithViewContext:(id)arg1 post:(id)arg2 feedPostOptions:(id)arg3 delegate:(id)arg4 parentPost:(id)arg5;
- (id)initWithViewContext:(id)arg1 post:(id)arg2 feedPostOptions:(id)arg3 delegate:(id)arg4;

@end

