//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AsyncDisplayKit/ASDisplayNode.h>

#import "ObjectObserverProtocol-Protocol.h"

@class FeedPostHlsVideoView, FeedPostImageNode, FeedPostOptions, NSString, Post;
@protocol FeedPostMediaContentNodeDelegate;

@interface FeedPostMediaContentNode : ASDisplayNode <ObjectObserverProtocol>
{
    Post *_post;
    id <FeedPostMediaContentNodeDelegate> _delegate;
    ASDisplayNode *_mediaNode;
    FeedPostOptions *_options;
}

- (void).cxx_destruct;
@property(retain, nonatomic) FeedPostOptions *options; // @synthesize options=_options;
@property(retain, nonatomic) ASDisplayNode *mediaNode; // @synthesize mediaNode=_mediaNode;
@property(nonatomic) __weak id <FeedPostMediaContentNodeDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) Post *post; // @synthesize post=_post;
- (id)createLegacyHLSVideoNodeForPost:(id)arg1 options:(id)arg2 viewContext:(id)arg3 delegate:(id)arg4 parentPost:(id)arg5;
- (id)createLegacyVideoNodeWithViewContext:(id)arg1 post:(id)arg2 options:(id)arg3 delegate:(id)arg4 parentPost:(id)arg5;
- (struct CGSize)mediaSizeForTargetWidth:(double)arg1;
- (id)layoutSpecThatFits:(CDStruct_90e057aa)arg1;
- (void)noLongerPastVisibilityThreshold;
- (void)didPassVisibilityThreshold;
- (void)didBecomeFullyVisible;
@property(readonly, nonatomic) FeedPostHlsVideoView *hlsVideoView;
- (id)initWithViewContext:(id)arg1 post:(id)arg2 options:(id)arg3 delegate:(id)arg4 parentPost:(id)arg5;
- (id)initWithViewContext:(id)arg1 post:(id)arg2 options:(id)arg3 delegate:(id)arg4;
@property(readonly, nonatomic) FeedPostImageNode *imageNode;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

