//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BaseCollectionViewCellNode.h"

#import "ChainedCarouselDisplaying-Protocol.h"
#import "FeedPostCollectionViewItem-Protocol.h"
#import "ObjectObserverProtocol-Protocol.h"
#import "VisibilityTrackable-Protocol.h"

@class ASDisplayNode, Carousel, CarouselContainerNode, FeedPostCommentBarNode, FeedPostContentNode, FeedPostEventBarNode, FeedPostModerateBarNode, FeedPostOptions, FeedPostTitleNode, NSString, Post, PostMetaViewModel, UIImage, _TtC6Reddit18FeedPostAwardsNode;
@protocol CarouselContainerNodeDelegate, FeedPostCellNodeDelegate><PillContainerNodeDelegate, ViewContext;

@interface FeedPostCellNode : BaseCollectionViewCellNode <VisibilityTrackable, ObjectObserverProtocol, ChainedCarouselDisplaying, FeedPostCollectionViewItem>
{
    Carousel *_chainedCarousel;
    Post *_post;
    FeedPostTitleNode *_titleNode;
    id <FeedPostCellNodeDelegate><PillContainerNodeDelegate> _delegate;
    id <CarouselContainerNodeDelegate> _carouselContainerNodeDelegate;
    id <ViewContext> _viewContext;
    FeedPostEventBarNode *_eventBarNode;
    _TtC6Reddit18FeedPostAwardsNode *_awardsNode;
    FeedPostContentNode *_contentNode;
    FeedPostCommentBarNode *_commentBarNode;
    FeedPostModerateBarNode *_modBarNode;
    FeedPostOptions *_options;
    PostMetaViewModel *_postMetaViewModel;
    ASDisplayNode *_chainedDiscoveryNodeSeparator;
    CarouselContainerNode *_chainedDiscoveryNode;
    ASDisplayNode *_separator;
}

- (void).cxx_destruct;
@property(retain, nonatomic) ASDisplayNode *separator; // @synthesize separator=_separator;
@property(retain, nonatomic) CarouselContainerNode *chainedDiscoveryNode; // @synthesize chainedDiscoveryNode=_chainedDiscoveryNode;
@property(retain, nonatomic) ASDisplayNode *chainedDiscoveryNodeSeparator; // @synthesize chainedDiscoveryNodeSeparator=_chainedDiscoveryNodeSeparator;
@property(retain, nonatomic) PostMetaViewModel *postMetaViewModel; // @synthesize postMetaViewModel=_postMetaViewModel;
@property(retain, nonatomic) FeedPostOptions *options; // @synthesize options=_options;
@property(retain, nonatomic) FeedPostModerateBarNode *modBarNode; // @synthesize modBarNode=_modBarNode;
@property(retain, nonatomic) FeedPostCommentBarNode *commentBarNode; // @synthesize commentBarNode=_commentBarNode;
@property(retain, nonatomic) FeedPostContentNode *contentNode; // @synthesize contentNode=_contentNode;
@property(retain, nonatomic) _TtC6Reddit18FeedPostAwardsNode *awardsNode; // @synthesize awardsNode=_awardsNode;
@property(retain, nonatomic) FeedPostEventBarNode *eventBarNode; // @synthesize eventBarNode=_eventBarNode;
@property(readonly, nonatomic) id <ViewContext> viewContext; // @synthesize viewContext=_viewContext;
@property(nonatomic) __weak id <CarouselContainerNodeDelegate> carouselContainerNodeDelegate; // @synthesize carouselContainerNodeDelegate=_carouselContainerNodeDelegate;
@property(nonatomic) __weak id <FeedPostCellNodeDelegate><PillContainerNodeDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) FeedPostTitleNode *titleNode; // @synthesize titleNode=_titleNode;
@property(readonly, nonatomic) Post *post; // @synthesize post=_post;
@property(retain, nonatomic) Carousel *chainedCarousel; // @synthesize chainedCarousel=_chainedCarousel;
- (id)voteTooltipAnchorView;
- (id)subscribeTooltipAnchorView;
- (void)updateContentViewsForData:(id)arg1 changeKeyPath:(id)arg2 oldValue:(id)arg3 newValue:(id)arg4;
- (void)debugLogVisibility:(id)arg1;
- (void)didExitVisibleStateWithVisibilityContext:(id)arg1;
- (void)didEnterVisibleStateWithVisibilityContext:(id)arg1;
- (void)didExitVisibleThresholdStateWithVisibilityContext:(id)arg1;
- (void)didExitFullyVisibleStateWithVisibilityContext:(id)arg1;
- (void)didEnterVisibleThresholdStateWithVisibilityContext:(id)arg1;
- (void)didEnterFullyVisibleStateWithVisibilityContext:(id)arg1;
- (void)didChangeMediaVisibilityWithContext:(id)arg1;
- (void)didChangeVisibilityWithContext:(id)arg1;
- (void)beginVisibilityTracking;
- (void)layoutDidFinish;
- (id)layoutSpecThatFits:(CDStruct_90e057aa)arg1;
- (void)createAwardsNodeIfNecessary;
- (void)createNodes;
@property(readonly, nonatomic) UIImage *previewImage;
- (id)initWithPost:(id)arg1 viewContext:(id)arg2 postMetaViewModel:(id)arg3 options:(id)arg4 carouselContainerNodeDelegate:(id)arg5 delegate:(id)arg6 visibilityTracker:(id)arg7;
- (id)initWithPost:(id)arg1 viewContext:(id)arg2 options:(id)arg3 carouselContainerNodeDelegate:(id)arg4 delegate:(id)arg5 visibilityTracker:(id)arg6;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

