//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AsyncDisplayKit/ASDisplayNode.h>

@class ASButtonNode, ASImageNode, ASTextNode, FocusVerticalRecommendation, NSArray;
@protocol FocusVerticalsDiscoveryFeedbackNodeDelegate;

@interface FocusVerticalsDiscoveryFeedbackNode : ASDisplayNode
{
    FocusVerticalRecommendation *_focusVerticalRecommendation;
    id <FocusVerticalsDiscoveryFeedbackNodeDelegate> _delegate;
    long long _status;
    ASButtonNode *_undoButton;
    ASTextNode *_promptTextNode;
    ASButtonNode *_notInterestedInCategoryButton;
    ASButtonNode *_notInterestedInSubredditButton;
    ASButtonNode *_subredditIsNotInCategoryButton;
    ASButtonNode *_recommendedTooOftenButton;
    NSArray *_lineSeparators;
    ASImageNode *_checkmarkIconNode;
    ASTextNode *_responseTextNode;
    ASTextNode *_showFewerTextNode;
}

- (void).cxx_destruct;
@property(retain, nonatomic) ASTextNode *showFewerTextNode; // @synthesize showFewerTextNode=_showFewerTextNode;
@property(retain, nonatomic) ASTextNode *responseTextNode; // @synthesize responseTextNode=_responseTextNode;
@property(retain, nonatomic) ASImageNode *checkmarkIconNode; // @synthesize checkmarkIconNode=_checkmarkIconNode;
@property(retain, nonatomic) NSArray *lineSeparators; // @synthesize lineSeparators=_lineSeparators;
@property(retain, nonatomic) ASButtonNode *recommendedTooOftenButton; // @synthesize recommendedTooOftenButton=_recommendedTooOftenButton;
@property(retain, nonatomic) ASButtonNode *subredditIsNotInCategoryButton; // @synthesize subredditIsNotInCategoryButton=_subredditIsNotInCategoryButton;
@property(retain, nonatomic) ASButtonNode *notInterestedInSubredditButton; // @synthesize notInterestedInSubredditButton=_notInterestedInSubredditButton;
@property(retain, nonatomic) ASButtonNode *notInterestedInCategoryButton; // @synthesize notInterestedInCategoryButton=_notInterestedInCategoryButton;
@property(retain, nonatomic) ASTextNode *promptTextNode; // @synthesize promptTextNode=_promptTextNode;
@property(retain, nonatomic) ASButtonNode *undoButton; // @synthesize undoButton=_undoButton;
@property(nonatomic) long long status; // @synthesize status=_status;
@property(retain, nonatomic) id <FocusVerticalsDiscoveryFeedbackNodeDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) FocusVerticalRecommendation *focusVerticalRecommendation; // @synthesize focusVerticalRecommendation=_focusVerticalRecommendation;
- (void)didTapRecommendedTooOftenButton;
- (void)didTapSubredditNotInCommunityButton;
- (void)didTapNotInterestedInSubredditButton;
- (void)didTapNotInterestedInCategoryButton;
- (void)didTapUndoButton;
- (void)refresh;
- (id)layoutSpecShowLessForSize:(CDStruct_90e057aa)arg1;
- (id)layoutSpecFeedbackGivenForSize:(CDStruct_90e057aa)arg1;
- (id)layoutSpecInitialForSize:(CDStruct_90e057aa)arg1;
- (id)layoutSpecThatFits:(CDStruct_90e057aa)arg1;
- (id)lineSeparatorAtIndex:(int)arg1;
- (void)createLineSeparators;
- (id)lineSeparator;
- (void)createShowFewerTextNode;
- (void)createResponseTextNode;
- (void)createCheckmarkIconNode;
- (void)createRecommendedTooOftenButtonNode;
- (void)createSubredditNotInCategoryButtonNode;
- (void)createNotInterestedInSubredditButtonNode;
- (void)createNotInterestedInCategoryButtonNode;
- (void)createPrompTextNode;
- (void)createUndoButton;
- (void)createNodes;
- (id)initWithFocusVerticalRecommendation:(id)arg1 delegate:(id)arg2;

@end

