//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString, Subreddit;

@interface FocusVerticalRecommendation : NSObject
{
    _Bool _isFeedbackEnabled;
    Subreddit *_subreddit;
    NSArray *_posts;
    Subreddit *_interactedSubreddit;
    NSString *_category;
    long long _focusVerticalRecommendationType;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) _Bool isFeedbackEnabled; // @synthesize isFeedbackEnabled=_isFeedbackEnabled;
@property(readonly, nonatomic) long long focusVerticalRecommendationType; // @synthesize focusVerticalRecommendationType=_focusVerticalRecommendationType;
@property(readonly, nonatomic) NSString *category; // @synthesize category=_category;
@property(readonly, nonatomic) Subreddit *interactedSubreddit; // @synthesize interactedSubreddit=_interactedSubreddit;
@property(readonly, copy, nonatomic) NSArray *posts; // @synthesize posts=_posts;
@property(readonly, nonatomic) Subreddit *subreddit; // @synthesize subreddit=_subreddit;
- (id)initWithSubreddit:(id)arg1 posts:(id)arg2 interactedSubreddit:(id)arg3 category:(id)arg4 focusVerticalRecommendationType:(long long)arg5 isFeedbackEnabled:(_Bool)arg6;

@end

