//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BaseFeedDisplayNode.h"

@class ASDisplayNode, ASTextNode, FeedPostOptions, FeedPostThumbnailNode, FocusVerticalsDiscoveryUnitViewModel, Post, Subreddit;
@protocol FocusVerticalsPostNodeDelegate, ViewContext;

@interface FocusVerticalsPostNode : BaseFeedDisplayNode
{
    Post *_post;
    Subreddit *_subreddit;
    FocusVerticalsDiscoveryUnitViewModel *_viewModel;
    id <FocusVerticalsPostNodeDelegate> _delegate;
    FeedPostOptions *_options;
    ASTextNode *_titleNode;
    ASTextNode *_scoreNode;
    ASDisplayNode *_backgroundNode;
    FeedPostThumbnailNode *_thumbnailNode;
    id <ViewContext> _viewContext;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) id <ViewContext> viewContext; // @synthesize viewContext=_viewContext;
@property(retain, nonatomic) FeedPostThumbnailNode *thumbnailNode; // @synthesize thumbnailNode=_thumbnailNode;
@property(retain, nonatomic) ASDisplayNode *backgroundNode; // @synthesize backgroundNode=_backgroundNode;
@property(retain, nonatomic) ASTextNode *scoreNode; // @synthesize scoreNode=_scoreNode;
@property(retain, nonatomic) ASTextNode *titleNode; // @synthesize titleNode=_titleNode;
@property(retain, nonatomic) FeedPostOptions *options; // @synthesize options=_options;
@property(nonatomic) __weak id <FocusVerticalsPostNodeDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) FocusVerticalsDiscoveryUnitViewModel *viewModel; // @synthesize viewModel=_viewModel;
@property(retain, nonatomic) Subreddit *subreddit; // @synthesize subreddit=_subreddit;
@property(retain, nonatomic) Post *post; // @synthesize post=_post;
- (void)didExitVisibleStateWithVisibilityContext:(id)arg1;
- (void)didTapNode:(id)arg1;
- (id)layoutSpecThatFits:(CDStruct_90e057aa)arg1;
- (void)configureBackgroundNode;
- (void)configureScoreNode;
- (void)configureTitleNode;
- (void)configureNodes;
- (void)createThumbnailNode;
- (void)createBackgroundNode;
- (void)createScoreNode;
- (void)createTitleNode;
- (void)createNodes;
- (id)initWithFocusVerticalsDiscoveryUnitViewModel:(id)arg1 viewContext:(id)arg2 post:(id)arg3 subreddit:(id)arg4 options:(id)arg5 visibilityOptions:(id)arg6;

@end

