//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import <Economy/GoldCoinMarketingPageHeaderCellDelegate-Protocol.h>
#import <Economy/GoldProductTableViewCellDelegate-Protocol.h>
#import <Economy/UITableViewDataSource-Protocol.h>
#import <Economy/UITableViewDelegate-Protocol.h>

@class BaseTableView, FeedSpinnerView, NSArray, NSLayoutConstraint, NSString, RedditService, UIImageView;
@protocol GoldCoinMarketingListDelegate;

@interface GoldCoinMarketingList : UIView <UITableViewDataSource, UITableViewDelegate, GoldProductTableViewCellDelegate, GoldCoinMarketingPageHeaderCellDelegate>
{
    _Bool _isEconStorefrontClaimEnabled;
    RedditService *_service;
    double _maxContentWidth;
    id <GoldCoinMarketingListDelegate> _delegate;
    UIImageView *_backgroundImageView;
    BaseTableView *_tableView;
    NSLayoutConstraint *_backgroundImageWidthConstraint;
    FeedSpinnerView *_loadingIndicatorView;
    NSArray *_products;
    struct UIEdgeInsets _preferredContentInset;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSArray *products; // @synthesize products=_products;
@property(retain, nonatomic) FeedSpinnerView *loadingIndicatorView; // @synthesize loadingIndicatorView=_loadingIndicatorView;
@property(retain, nonatomic) NSLayoutConstraint *backgroundImageWidthConstraint; // @synthesize backgroundImageWidthConstraint=_backgroundImageWidthConstraint;
@property(retain, nonatomic) BaseTableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) UIImageView *backgroundImageView; // @synthesize backgroundImageView=_backgroundImageView;
@property(readonly, nonatomic) _Bool isEconStorefrontClaimEnabled; // @synthesize isEconStorefrontClaimEnabled=_isEconStorefrontClaimEnabled;
@property(readonly, nonatomic) __weak id <GoldCoinMarketingListDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) double maxContentWidth; // @synthesize maxContentWidth=_maxContentWidth;
@property(readonly, nonatomic) struct UIEdgeInsets preferredContentInset; // @synthesize preferredContentInset=_preferredContentInset;
@property(readonly, nonatomic) RedditService *service; // @synthesize service=_service;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)goldProductTableViewCellDidTap:(id)arg1;
- (void)goldCoinMarketingPageHeaderCellDidTapLearnMore:(id)arg1;
- (void)hideLoadingIndicator;
- (void)showLoadingIndicator;
- (void)fetchGoldProductsIfNecessary;
- (void)updateProductItems;
- (struct UIEdgeInsets)contentInsetForRowAtIndexPath:(id)arg1 increaseTopPaddingForTheFirstCell:(_Bool)arg2;
- (void)handleFetchFailure;
- (void)handleFetchSuccess;
- (void)layoutSubviews;
- (id)initWithService:(id)arg1 preferredContentInset:(struct UIEdgeInsets)arg2 maxContentWidth:(double)arg3 delegate:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

