//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "PopupViewController.h"

@class BaseButton, BaseView, GoldProduct, UIImageView, UILabel;
@protocol AccountContext;

@interface GoldCoinPurchaseSuccessViewController : PopupViewController
{
    id <AccountContext> _accountContext;
    UIImageView *_productImageView;
    UILabel *_successTitleLabel;
    UILabel *_messageLabel;
    GoldProduct *_product;
    BaseButton *_actionButton;
    BaseView *_dialogContentView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) BaseView *dialogContentView; // @synthesize dialogContentView=_dialogContentView;
@property(retain, nonatomic) BaseButton *actionButton; // @synthesize actionButton=_actionButton;
@property(retain, nonatomic) GoldProduct *product; // @synthesize product=_product;
@property(retain, nonatomic) UILabel *messageLabel; // @synthesize messageLabel=_messageLabel;
@property(retain, nonatomic) UILabel *successTitleLabel; // @synthesize successTitleLabel=_successTitleLabel;
@property(retain, nonatomic) UIImageView *productImageView; // @synthesize productImageView=_productImageView;
@property(readonly, nonatomic) id <AccountContext> accountContext; // @synthesize accountContext=_accountContext;
- (void)setupViews;
- (void)actionButtonDidTap:(id)arg1;
- (void)closeButtonDidTap:(id)arg1;
- (void)viewDidLoad;
- (id)initWithAccountContext:(id)arg1 product:(id)arg2;

@end

