//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "PopupViewController.h"

#import "AttributedLabelRegularDelegate-Protocol.h"

@class AttributedLabelRegular, BaseButton, ImagePopupContentView, NSString;
@protocol ImagePopupViewControllerActiveDelegate, ImagePopupViewControllerDelegate;

@interface ImagePopupViewController : PopupViewController <AttributedLabelRegularDelegate>
{
    id <ImagePopupViewControllerDelegate> _delegate;
    id <ImagePopupViewControllerActiveDelegate> _activeDelegate;
    id _context;
    BaseButton *_confirmButton;
    BaseButton *_cancelButton;
    BaseButton *_activeButton;
}

+ (id)awardDetailsInfoDialogMetadataViewForAward:(id)arg1 gildingTarget:(unsigned long long)arg2 subreddit:(id)arg3;
+ (id)inAppPurchasePopupWithAccountContext:(id)arg1 image:(id)arg2 title:(id)arg3 message:(id)arg4 confirmText:(id)arg5 cancelText:(id)arg6 actionHandler:(CDUnknownBlockType)arg7;
+ (id)cancelPremiumOfferDialogWithAccountContext:(id)arg1 offer:(id)arg2 actionHandler:(CDUnknownBlockType)arg3;
+ (id)awardDetailsInfoDialogWithAccountContext:(id)arg1 award:(id)arg2 gildingTarget:(unsigned long long)arg3 subreddit:(id)arg4;
+ (id)gildingFailureAfterPurchaseDialogWithAccountContext:(id)arg1 actionHandler:(CDUnknownBlockType)arg2;
+ (id)inAppPurchaseValidationErrorDialogWithAccountContext:(id)arg1 packageType:(long long)arg2 actionHandler:(CDUnknownBlockType)arg3;
+ (id)inAppPurchaseValidationErrorDialogWithAccountContext:(id)arg1 gildingTarget:(unsigned long long)arg2 actionHandler:(CDUnknownBlockType)arg3;
+ (id)inAppPurchaseTransactionDeferredDialogWithAccountContext:(id)arg1 target:(unsigned long long)arg2 actionHandler:(CDUnknownBlockType)arg3;
+ (id)inAppPurchaseTransactionInFlightDialogWithAccountContext:(id)arg1 productDescription:(id)arg2 actionHandler:(CDUnknownBlockType)arg3;
+ (id)inAppPurchaseTransactionInFlightDialogWithAccountContext:(id)arg1 product:(id)arg2 actionHandler:(CDUnknownBlockType)arg3;
+ (id)roadblockForRoadblockViewModel:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) BaseButton *activeButton; // @synthesize activeButton=_activeButton;
@property(retain, nonatomic) BaseButton *cancelButton; // @synthesize cancelButton=_cancelButton;
@property(retain, nonatomic) BaseButton *confirmButton; // @synthesize confirmButton=_confirmButton;
@property(retain, nonatomic) id context; // @synthesize context=_context;
@property(nonatomic) __weak id <ImagePopupViewControllerActiveDelegate> activeDelegate; // @synthesize activeDelegate=_activeDelegate;
@property(nonatomic) __weak id <ImagePopupViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)attributedLabelRegular:(id)arg1 didSelectLinkWithURL:(id)arg2;
@property(readonly, nonatomic) AttributedLabelRegular *bodyMarkdownTextLabel;
@property(readonly, nonatomic) ImagePopupContentView *imagePopupView;
- (void)didTapActiveButton:(id)arg1;
- (void)didTapCancelButton:(id)arg1;
- (void)didTapConfirmButton:(id)arg1;
- (void)didTapCloseButton:(id)arg1;
- (id)initWithAccountContext:(id)arg1 title:(id)arg2 animatedImageURL:(id)arg3 placeholderImage:(id)arg4 attributedBody:(id)arg5 confirmText:(id)arg6 cancelText:(id)arg7 metadataView:(id)arg8;
- (id)initWithAccountContext:(id)arg1 title:(id)arg2 image:(id)arg3 body:(id)arg4 confirmText:(id)arg5 activeText:(id)arg6 bottomStackViewAxis:(long long)arg7;
- (id)initWithAccountContext:(id)arg1 title:(id)arg2 imageURL:(id)arg3 placeholderImage:(id)arg4 attributedBody:(id)arg5 confirmText:(id)arg6 cancelText:(id)arg7 metadataView:(id)arg8;
- (id)initWithAccountContext:(id)arg1 title:(id)arg2 image:(id)arg3 attributedBody:(id)arg4 confirmText:(id)arg5 cancelText:(id)arg6;
- (id)initWithAccountContext:(id)arg1 title:(id)arg2 image:(id)arg3 body:(id)arg4 confirmText:(id)arg5 cancelText:(id)arg6;
- (id)initWithAccountContext:(id)arg1 imagePopupView:(id)arg2 confirmText:(id)arg3 activeText:(id)arg4;
- (id)initWithAccountContext:(id)arg1 imagePopupView:(id)arg2 confirmText:(id)arg3 cancelText:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

