//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BaseViewController.h"

@class BaseButton, BaseLabel, NewUserIntroAnimationView, UIImageView;
@protocol AccountContext, IntroViewControllerDelegate;

@interface IntroViewController : BaseViewController
{
    _Bool _enableAnimation;
    _Bool _animationHasPlayed;
    id <IntroViewControllerDelegate> _delegate;
    id <AccountContext> _accountContext;
    BaseButton *_loginButton;
    BaseButton *_signupButton;
    BaseButton *_skipButton;
    UIImageView *_backgroundImageView;
    UIImageView *_logoImageView;
    NewUserIntroAnimationView *_animationView;
    BaseLabel *_titleLabel;
    BaseLabel *_exploreLabel;
    BaseLabel *_conversationsLabel;
}

- (void).cxx_destruct;
@property(retain, nonatomic) BaseLabel *conversationsLabel; // @synthesize conversationsLabel=_conversationsLabel;
@property(retain, nonatomic) BaseLabel *exploreLabel; // @synthesize exploreLabel=_exploreLabel;
@property(retain, nonatomic) BaseLabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) NewUserIntroAnimationView *animationView; // @synthesize animationView=_animationView;
@property(nonatomic) _Bool animationHasPlayed; // @synthesize animationHasPlayed=_animationHasPlayed;
@property(retain, nonatomic) UIImageView *logoImageView; // @synthesize logoImageView=_logoImageView;
@property(retain, nonatomic) UIImageView *backgroundImageView; // @synthesize backgroundImageView=_backgroundImageView;
@property(retain, nonatomic) BaseButton *skipButton; // @synthesize skipButton=_skipButton;
@property(retain, nonatomic) BaseButton *signupButton; // @synthesize signupButton=_signupButton;
@property(retain, nonatomic) BaseButton *loginButton; // @synthesize loginButton=_loginButton;
@property(retain, nonatomic) id <AccountContext> accountContext; // @synthesize accountContext=_accountContext;
@property(nonatomic) _Bool enableAnimation; // @synthesize enableAnimation=_enableAnimation;
@property(nonatomic) __weak id <IntroViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (id)analyticsScreenViewName;
- (void)skipButtonTapped:(id)arg1;
- (void)authenticateButtonTapped:(id)arg1;
- (void)layoutViewsForFrame:(struct CGRect)arg1;
- (void)configureViewsHidden:(_Bool)arg1 animated:(_Bool)arg2;
- (void)viewDidLoad;
- (void)configureViewAppearance;
- (void)viewWillAppear:(_Bool)arg1;
- (void)playAnimation;
- (void)viewDidAppear:(_Bool)arg1;
- (id)initWithAccountContext:(id)arg1;
- (_Bool)prefersStatusBarHidden;

@end

