//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <RedditCore/NSCopying-Protocol.h>
#import <RedditCore/NSObject-Protocol.h>

@class NSString;

@protocol LegacyKeychainAdapter <NSObject, NSCopying>
@property(readonly, copy, nonatomic) NSString *identifier;
- (_Bool)removeAllObjects;
- (_Bool)setString:(NSString *)arg1 forKey:(NSString *)arg2;
- (NSString *)stringForKey:(NSString *)arg1;
@end

