//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface LiveStreamSubscriptionDetails : NSObject
{
    _Bool _isSubscribedToSubreddit;
    _Bool _isFollowingBroadcasterProfile;
}

@property(readonly, nonatomic) _Bool isFollowingBroadcasterProfile; // @synthesize isFollowingBroadcasterProfile=_isFollowingBroadcasterProfile;
@property(readonly, nonatomic) _Bool isSubscribedToSubreddit; // @synthesize isSubscribedToSubreddit=_isSubscribedToSubreddit;
- (id)initWithData:(id)arg1;

@end

