//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "CaptureManager.h"

@class LoginCaptureScreen, RedditService, TwoFactorCaptureScreen;

@interface LoginCaptureManager : CaptureManager
{
    RedditService *_capturedRedditService;
    LoginCaptureScreen *_loginScreen;
    TwoFactorCaptureScreen *_twoFactorScreen;
}

- (void).cxx_destruct;
@property(retain, nonatomic) TwoFactorCaptureScreen *twoFactorScreen; // @synthesize twoFactorScreen=_twoFactorScreen;
@property(retain, nonatomic) LoginCaptureScreen *loginScreen; // @synthesize loginScreen=_loginScreen;
@property(retain, nonatomic) RedditService *capturedRedditService; // @synthesize capturedRedditService=_capturedRedditService;
- (void)handleAccountManagerError:(id)arg1;
- (void)checkAuthCodeWithCompletion:(CDUnknownBlockType)arg1 progressHandler:(CDUnknownBlockType)arg2;
- (void)loginWithCompletion:(CDUnknownBlockType)arg1 progressHandler:(CDUnknownBlockType)arg2;
- (void)didFinishScreen:(id)arg1 withCompletion:(CDUnknownBlockType)arg2 progressHandler:(CDUnknownBlockType)arg3;
- (void)screenDidAppear:(id)arg1;
- (id)initWithAccountContext:(id)arg1 analyticsSource:(id)arg2;

@end

