//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <RedditCore/NSURLRequestProcessor-Protocol.h>
#import <RedditCore/NSURLResponseProcessor-Protocol.h>

@class NSString, NSUserDefaults;

@interface Loid : NSObject <NSURLRequestProcessor, NSURLResponseProcessor>
{
    NSString *_pk;
    NSUserDefaults *_userDefaults;
}

@property(retain, nonatomic) NSUserDefaults *userDefaults; // @synthesize userDefaults=_userDefaults;
@property(retain, nonatomic) NSString *pk; // @synthesize pk=_pk;
- (void).cxx_destruct;
@property(readonly, copy) NSString *debugDescription;
- (void)processResponse:(id)arg1;
- (void)processRequest:(id)arg1;
@property(copy, nonatomic) NSString *fullTokenLoid;
- (id)tokenComponents;
- (id)createdDate;
@property(readonly, nonatomic) NSString *created;
@property(readonly, nonatomic) NSString *userId;
@property(readonly, nonatomic) NSString *loid;
@property(readonly, nonatomic) NSString *userDefaultsKey;
- (id)initWithAccountPk:(id)arg1 userDefaults:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

