//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "PostViewController.h"

#import "LinkViewControllerDelegate-Protocol.h"

@class APIError, BaseTextView, NSString, UIView, _TtC6Reddit29PollPostOptionsViewController;

@interface PollPostViewController : PostViewController <LinkViewControllerDelegate>
{
    BaseTextView *_postView;
    UIView *_separatorView;
    _TtC6Reddit29PollPostOptionsViewController *_postPollOptionsViewController;
    APIError *_formatValidationError;
    NSString *_postViewPlaceholder;
    NSString *_titleViewPlaceholder;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) NSString *titleViewPlaceholder; // @synthesize titleViewPlaceholder=_titleViewPlaceholder;
@property(readonly, nonatomic) NSString *postViewPlaceholder; // @synthesize postViewPlaceholder=_postViewPlaceholder;
@property(retain, nonatomic) APIError *formatValidationError; // @synthesize formatValidationError=_formatValidationError;
@property(retain, nonatomic) _TtC6Reddit29PollPostOptionsViewController *postPollOptionsViewController; // @synthesize postPollOptionsViewController=_postPollOptionsViewController;
@property(retain, nonatomic) UIView *separatorView; // @synthesize separatorView=_separatorView;
@property(retain, nonatomic) BaseTextView *postView; // @synthesize postView=_postView;
- (id)analyticsPostComposerType;
- (id)analyticsScreenViewName;
- (void)linkViewControllerDidTapInsert:(id)arg1;
- (void)textView:(id)arg1 didChangeToNewSize:(struct CGSize)arg2;
- (_Bool)baseTextView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (_Bool)textViewShouldBeginEditing:(id)arg1;
- (void)didTapPostButton:(id)arg1;
- (id)populateSubmittedPost;
- (void)didTapCloseLink;
- (void)didTapLinkButton;
- (void)testAndShowUnallowedPostDisplayTypeWarning;
- (void)configureWithSubreddit:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)systemLayoutFittingSizeDidChangeForChildContentContainer:(id)arg1;
- (void)layoutTextFieldsInScroller;
- (void)layoutViewsForFrame:(struct CGRect)arg1;
- (void)viewDidLoad;
- (void)configureWithPostToEdit:(id)arg1;
- (id)powerupsMarketingBadgeView;
- (id)postErrorSeparator;
- (id)titleErrorSeparator;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

