//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface PostPollOption : NSObject
{
    NSString *_optionId;
    NSString *_text;
    long long _voteCount;
}

- (void).cxx_destruct;
@property(nonatomic) long long voteCount; // @synthesize voteCount=_voteCount;
@property(readonly, copy, nonatomic) NSString *text; // @synthesize text=_text;
@property(readonly, copy, nonatomic) NSString *optionId; // @synthesize optionId=_optionId;
- (id)initWithData:(id)arg1;
- (id)initWithGraphQLData:(id)arg1;

@end

