//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <RedditCore/Post.h>

@interface Post (Economy)
- (_Bool)isLastGivenAward:(id)arg1 accountPk:(id)arg2;
- (id)orderedAwardingTotalsWithAccountPk:(id)arg1;
@end

