//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface PowerupsMarketingBadgeView : UIView
{
    // Error parsing type: , name: horizontalStack
    // Error parsing type: , name: imageView
    // Error parsing type: , name: textLabel
    // Error parsing type: , name: badgeType
    // Error parsing type: , name: workItem
    // Error parsing type: , name: badgeVisibilityKey
    // Error parsing type: , name: powerupsInfo
    // Error parsing type: , name: didTapCallToAction
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)didTap:(id)arg1;
- (void)didSwipe:(id)arg1;
- (void)showForDuration:(double)arg1;
- (void)configureWithElapsed:(double)arg1 duration:(double)arg2;
- (void)setBadgeVisibilityKey:(id)arg1;
- (void)setPowerupsInfo:(id)arg1;
- (void)embedCenterBottomIn:(id)arg1;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;
- (id)initWithType:(long long)arg1;
@property(nonatomic, copy) CDUnknownBlockType didTapCallToAction;

@end

