//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface PowerupsTierInfo : NSObject
{
    long long _tier;
    long long _cost;
    long long _benefits;
}

@property(readonly, nonatomic) long long benefits; // @synthesize benefits=_benefits;
@property(readonly, nonatomic) long long cost; // @synthesize cost=_cost;
@property(readonly, nonatomic) long long tier; // @synthesize tier=_tier;
- (id)initWithGraphQLData:(id)arg1;

@end

