//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@interface PowerupsMarketingSheetViewController : UIViewController
{
    // Error parsing type: , name: collectionView
    // Error parsing type: , name: divider
    // Error parsing type: , name: unlockCountView
    // Error parsing type: , name: unlockProgressButton
    // Error parsing type: , name: closeButton
    // Error parsing type: , name: service
    // Error parsing type: , name: serviceError
    // Error parsing type: , name: subreddit
    // Error parsing type: , name: viewModel
    // Error parsing type: , name: selectedLevelIndex
}

- (void).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)didTapActionButton;
- (void)didTapCloseButton;
- (void)viewDidLoad;
- (id)initWithCoder:(id)arg1;
- (id)initWith:(id)arg1 powerupsInfo:(id)arg2 preselectedBenefit:(long long)arg3 accountPk:(id)arg4;

@end

