//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface PremiumCancelOffer : NSObject
{
    NSString *_productId;
    unsigned long long _bonusCoins;
    NSString *_productDescription;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) NSString *productDescription; // @synthesize productDescription=_productDescription;
@property(readonly, nonatomic) unsigned long long bonusCoins; // @synthesize bonusCoins=_bonusCoins;
@property(readonly, nonatomic) NSString *productId; // @synthesize productId=_productId;
- (id)initWithData:(id)arg1;

@end

