//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDate, NSNumber;

@interface PremiumSubscriptionInfo : NSObject
{
    _Bool _isPremiumMember;
    NSDate *_nextRenewalOn;
    NSNumber *_cancelOfferBonusCoins;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) _Bool isPremiumMember; // @synthesize isPremiumMember=_isPremiumMember;
@property(readonly, nonatomic) NSNumber *cancelOfferBonusCoins; // @synthesize cancelOfferBonusCoins=_cancelOfferBonusCoins;
@property(readonly, nonatomic) NSDate *nextRenewalOn; // @synthesize nextRenewalOn=_nextRenewalOn;
- (id)initWithData:(id)arg1;

@end

