//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BaseViewController.h"

@class RedditService, UIStackView;
@protocol AccountContext;

@interface RedditPremiumPreferencesViewController : BaseViewController
{
    _Bool _cancelOfferShown;
    id <AccountContext> _accountContext;
    UIStackView *_contentStackView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIStackView *contentStackView; // @synthesize contentStackView=_contentStackView;
@property(nonatomic) _Bool cancelOfferShown; // @synthesize cancelOfferShown=_cancelOfferShown;
@property(readonly, nonatomic) id <AccountContext> accountContext; // @synthesize accountContext=_accountContext;
- (id)lineSeparatorView;
- (id)spacerWithHeight:(double)arg1;
- (id)buttonWithTitle:(id)arg1 action:(SEL)arg2;
- (id)labelWithText:(id)arg1;
- (id)labelWithTitle:(id)arg1;
- (void)manageWebSubscriptionDidTap:(id)arg1;
- (void)manageInAppSubscriptionDidTap:(id)arg1;
- (_Bool)shouldShowCancellationOffer;
- (void)showCancellationOffer;
- (void)setupViewsForNonSubscriber;
- (void)setupViewsForSubscriber;
- (void)viewDidLoad;
@property(readonly, nonatomic) RedditService *service;
- (id)initWithAccountContext:(id)arg1;

@end

