//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSHashTable, RUITheme, UIWindow;

@interface RUIThemeGuidance : NSObject
{
    RUITheme *_currentTheme;
    double _lastUpdatedTimestamp;
    UIWindow *_window;
    NSHashTable *_observerPool;
}

+ (id)sharedGuidance;
- (void).cxx_destruct;
@property(retain, nonatomic) NSHashTable *observerPool; // @synthesize observerPool=_observerPool;
@property(retain, nonatomic) UIWindow *window; // @synthesize window=_window;
@property(readonly, nonatomic) double lastUpdatedTimestamp; // @synthesize lastUpdatedTimestamp=_lastUpdatedTimestamp;
@property(retain, nonatomic) RUITheme *currentTheme; // @synthesize currentTheme=_currentTheme;
- (long long)scrollViewIndicatorStyleForThemeType:(unsigned long long)arg1;
- (void)performAppearanceAPIUpdatesForTheme:(id)arg1;
- (void)notifyThemeObserversWithOnVisibleObserversDidUpdate:(CDUnknownBlockType)arg1;
- (id)contrastSafeColorFromColor:(id)arg1;
- (void)removeThemeObserver:(id)arg1;
- (void)addThemeObserver:(id)arg1;
- (void)updateCurrentTheme:(id)arg1 onVisibleObserversDidUpdate:(CDUnknownBlockType)arg2;
- (id)init;

@end

