//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class Comment, GildingEventLogger, NSDictionary, NSIndexPath, NSNumber, NSOrderedSet, Post, Subreddit, _TtC7Economy19AwardSelectionState, _TtC7Economy21AwardSelectionOptions;
@protocol AccountContext, SelectAwardPresentable, UIScrollViewDelegate;

@interface SelectAwardPresenter : NSObject
{
    _Bool _isLoading;
    id <AccountContext> _accountContext;
    id <SelectAwardPresentable> _presentable;
    id <UIScrollViewDelegate> _scrollingDelegate;
    Subreddit *_subreddit;
    NSNumber *_subredditCoins;
    _TtC7Economy21AwardSelectionOptions *_options;
    _TtC7Economy19AwardSelectionState *_selectionState;
    Post *_post;
    Comment *_comment;
    NSOrderedSet *_sections;
    NSDictionary *_awardsBySection;
    NSDictionary *_awardViewModelById;
    GildingEventLogger *_eventLogger;
}

+ (id)keyPathsForValuesAffectingCoinBalance;
- (void).cxx_destruct;
@property(nonatomic) _Bool isLoading; // @synthesize isLoading=_isLoading;
@property(retain, nonatomic) GildingEventLogger *eventLogger; // @synthesize eventLogger=_eventLogger;
@property(retain, nonatomic) NSDictionary *awardViewModelById; // @synthesize awardViewModelById=_awardViewModelById;
@property(retain, nonatomic) NSDictionary *awardsBySection; // @synthesize awardsBySection=_awardsBySection;
@property(retain, nonatomic) NSOrderedSet *sections; // @synthesize sections=_sections;
@property(readonly, nonatomic) Comment *comment; // @synthesize comment=_comment;
@property(readonly, nonatomic) Post *post; // @synthesize post=_post;
@property(readonly, nonatomic) _TtC7Economy19AwardSelectionState *selectionState; // @synthesize selectionState=_selectionState;
@property(readonly, copy, nonatomic) _TtC7Economy21AwardSelectionOptions *options; // @synthesize options=_options;
@property(retain, nonatomic) NSNumber *subredditCoins; // @synthesize subredditCoins=_subredditCoins;
@property(retain, nonatomic) Subreddit *subreddit; // @synthesize subreddit=_subreddit;
@property(nonatomic) __weak id <UIScrollViewDelegate> scrollingDelegate; // @synthesize scrollingDelegate=_scrollingDelegate;
@property(nonatomic) __weak id <SelectAwardPresentable> presentable; // @synthesize presentable=_presentable;
@property(readonly, nonatomic) id <AccountContext> accountContext; // @synthesize accountContext=_accountContext;
- (void)didTapReloadButton;
- (void)didSelectItemAtIndexPath:(id)arg1;
- (void)didLoad;
- (void)handleFetchUsableAwards:(id)arg1 subredditCoins:(id)arg2 error:(id)arg3;
- (void)fetchUsableAwards;
- (void)handleFetchSubreddit:(id)arg1 usableAwards:(id)arg2 subredditCoins:(id)arg3 error:(id)arg4;
- (void)fetchSubreddit;
- (void)fetchData;
@property(readonly, nonatomic) NSIndexPath *selectedIndexPath;
- (long long)sectionTypeAtIndex:(unsigned long long)arg1;
- (id)viewModelForItemAtIndexPath:(id)arg1;
- (id)sectionHeaderViewModelForSection:(unsigned long long)arg1;
- (_Bool)canSelectItemAtIndexPath:(id)arg1;
- (_Bool)shouldShowFooterImageForSection:(unsigned long long)arg1;
- (unsigned long long)numberOfItemsInSection:(unsigned long long)arg1;
@property(readonly, nonatomic) unsigned long long numberOfSections;
@property(readonly, nonatomic) unsigned long long gildingTarget;
@property(readonly, nonatomic) long long coinBalance;
- (id)initWithAccountContext:(id)arg1 post:(id)arg2 comment:(id)arg3 options:(id)arg4 selectionState:(id)arg5 eventLogger:(id)arg6;

@end

