//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Economy/ServiceRegistration.h>

@interface ServiceRegistration (Economy)
- (id)initWithKind:(id)arg1 required:(_Bool)arg2 preload:(_Bool)arg3 serviceMaker:(CDUnknownBlockType)arg4;
@end

