//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDate, NSString;

@interface SubredditSupporter : NSObject
{
    NSString *_identifier;
    NSString *_name;
    NSString *_iconURLString;
    NSDate *_startedAt;
    NSDate *_lastSupportedAt;
    long long _score;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) long long score; // @synthesize score=_score;
@property(readonly, nonatomic) NSDate *lastSupportedAt; // @synthesize lastSupportedAt=_lastSupportedAt;
@property(readonly, nonatomic) NSDate *startedAt; // @synthesize startedAt=_startedAt;
@property(readonly, nonatomic) NSString *iconURLString; // @synthesize iconURLString=_iconURLString;
@property(readonly, nonatomic) NSString *name; // @synthesize name=_name;
@property(readonly, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (id)initWithGraphQLData:(id)arg1;

@end

