//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "PostViewController.h"

#import "LinkViewControllerDelegate-Protocol.h"

@class BaseTextView, NSString, UIView;

@interface TextPostViewController : PostViewController <LinkViewControllerDelegate>
{
    BaseTextView *_postView;
    UIView *_separatorView;
    NSString *_postViewPlaceholder;
    NSString *_titleViewPlaceholder;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) NSString *titleViewPlaceholder; // @synthesize titleViewPlaceholder=_titleViewPlaceholder;
@property(readonly, nonatomic) NSString *postViewPlaceholder; // @synthesize postViewPlaceholder=_postViewPlaceholder;
@property(retain, nonatomic) UIView *separatorView; // @synthesize separatorView=_separatorView;
@property(retain, nonatomic) BaseTextView *postView; // @synthesize postView=_postView;
- (id)analyticsPostComposerType;
- (id)analyticsScreenViewName;
- (void)linkViewControllerDidTapInsert:(id)arg1;
- (void)textView:(id)arg1 didChangeToNewSize:(struct CGSize)arg2;
- (_Bool)baseTextView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (_Bool)textViewShouldBeginEditing:(id)arg1;
- (void)didTapPostButton:(id)arg1;
- (id)populateSubmittedPost;
- (void)didTapCloseLink;
- (void)didTapLinkButton;
- (void)testAndShowUnallowedPostDisplayTypeWarning;
- (void)configureWithSubreddit:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)layoutTextFieldsInScroller;
- (void)layoutViewsForFrame:(struct CGRect)arg1;
- (void)viewDidLoad;
- (void)configureWithPostToEdit:(id)arg1;
- (id)powerupsMarketingBadgeView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

