//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class Account, AdEventsManager, AnalyticsManager, ExperimentManager, GivenAwardsManager, LegacyExperimentManager, RUI, SubredditManager, VisibilityTracker;

@protocol ViewContext <NSObject>
@property(nonatomic, readonly) AdEventsManager *adEventsManager;
@property(nonatomic, readonly) VisibilityTracker *visibilityTracker;
@property(nonatomic, readonly) AnalyticsManager *analyticsManager;
@property(nonatomic, readonly) Account *account;
@property(nonatomic, readonly) LegacyExperimentManager *legacyExperimentManager;
@property(nonatomic, readonly) ExperimentManager *experimentManager;
@property(nonatomic, readonly) RUI *rui;
@property(nonatomic, readonly) GivenAwardsManager *givenAwardsManager;
@property(nonatomic, readonly) SubredditManager *subredditManager;
@end

